// Problèmes en anglais (#167) : textes seulement, indexés par id de problème (table `puzzles` et lots locaux).
// Positions, réponses et coordonnées restent celles du français. Vocabulaire : docs/localisation/glossaire.md,
// section « Leçons en anglais ». Vérifié par src/content/problemes.en.test.ts. Traduits par difficulté croissante.
export interface TexteProbleme { title: string; prompt: string; explanation?: string; refutation?: string }

export const PROBLEMES_EN: Record<string, TexteProbleme> = {
  a01: {
    title: 'First capture',
    prompt: 'Capture the marked white stone right now.',
    explanation: "Well done! The empty points right next to a stone are its liberties. The white stone had only one left, E4: it was in atari. By playing E4, you fill its last liberty and capture it.",
    refutation: 'Not yet. The white stone still has an empty point next to it, at E4. As long as that point is empty, it stays on the board.',
  },
  n01: {
    title: 'Two stones at once',
    prompt: 'Capture the marked stone in one move.',
    explanation: "Well done! The stones at E5 and E4 are side by side: they form a chain. A chain shares its liberties, the empty points right next to it. Only one is left, E3: the chain is in atari. You fill it and capture both stones.",
    refutation: 'Not quite. The two white stones have only one liberty, E3. If you play elsewhere, White extends to E3 and gets three liberties back.',
  },
  a02: {
    title: 'Capture on the edge',
    prompt: 'Capture the marked white stone on the edge right now.',
    explanation: 'Correct! The liberties of a stone are the empty points right next to it. On the edge, it starts with only three. Here, only one was left, E2: the stone was in atari, and E2 captures it.',
    refutation: 'Not yet. On the edge, a stone has fewer liberties. This one has only one left: look for the empty point just above it.',
  },
  n02: {
    title: 'The bigger one first',
    prompt: 'Two white groups are in atari (only one liberty). Capture the bigger one, marked, in one move.',
    explanation: 'Well done! F1 fills the last liberty of the three bottom stones: you capture them all. When two groups are in atari, take the bigger one first.',
    refutation: 'Not quite. At C4, you take one stone, but White plays F1: the three bottom stones have two liberties again, E1 and F2.',
  },
  a03: {
    title: 'Capture in the corner',
    prompt: 'Capture the marked white stone in the corner right now.',
    explanation: 'Nice move! The liberties of a stone are the empty points right next to it. In the corner, there are only two. Your stone at B1 took one, so the white stone was in atari (only one liberty), and A2 captures it.',
    refutation: 'Not yet. In the corner, a stone starts with only two liberties. Your stone at B1 already takes one: the other is left.',
  },
  e01: {
    title: 'Two stones in the center',
    prompt: 'Capture both white stones right now.',
    explanation: "Well done! A group's liberties are the empty points next to it. These two stones had only one left, E4: they were in atari. At E4, you capture them both.",
    refutation: 'Not yet. The two white stones are side by side: they form a group and share their liberties. Only one empty point is still next to them.',
  },
  a15: {
    title: 'Capture on the side',
    prompt: 'Capture the marked white stone on the left edge right now.',
    explanation: 'Correct! The liberties of a stone are the empty points right next to it. On the edge, it has only three. Your stones at A6 and B5 took two: the stone was in atari (only one liberty), and A4 captures it.',
    refutation: 'Not yet. On the edge, the white stone starts with only three empty points next to it. Your stones take two: the last one is left, just below.',
  },
  n03: {
    title: 'Save before you take',
    prompt: 'Your marked stone is in atari: it has only one liberty left. Save it.',
    explanation: 'Well done! At E4, your stone extends: your two stones form a chain with three liberties, D4, F4 and E3. It is out of danger. Taking B8 was tempting, but White would have captured your stone at E4.',
    refutation: 'Not quite. You take B8, but White plays E4 and captures your stone. When one of your stones is in atari, save it first.',
  },
  a04: {
    title: 'Two stones on the edge',
    prompt: 'Capture the two white stones on the edge right now.',
    explanation: 'Perfect! Two stones side by side form a group: they live and die together. This group had only one liberty left (an empty point next to it), E2. It was in atari: E2 takes both stones at once.',
    refutation: 'Not yet. The two white stones are side by side: they form one group and share their liberties. Only one is left.',
  },
  e02: {
    title: 'Three stones on the edge',
    prompt: 'Capture the three white stones on the edge right now.',
    explanation: "Correct! Stones side by side form a group, and its liberties are the empty points next to it. Here, only one was left, E2: the group was in atari. You take three stones at once.",
    refutation: 'Not yet. The three white stones on the edge form one group. Look all around it: only one empty point is left.',
  },
  n04: {
    title: 'Toward the center',
    prompt: 'Your marked stone is in atari. Save it.',
    explanation: 'Well done! C7 extends your stone toward the center. Your two stones have three liberties, B7, D7 and C6: they can breathe. The white stone at H3 is in atari too, but it can wait.',
    refutation: 'Not quite. White plays C7 and captures your stone. Its only liberty was C7: that was the point to play.',
  },
  a05: {
    title: 'Two stones in the corner',
    prompt: 'Capture the two white stones in the corner right now.',
    explanation: 'Very good! The stones at A1 and A2 are side by side: they are a group. Its liberties, the empty points next to it, were down to A3. It was in atari; A3 captures both stones.',
    refutation: 'Not yet. The two white stones in the corner form one group. Count its liberties: only one empty point is left, above it.',
  },
  b1: {
    title: 'Capture the stone',
    prompt: 'The marked white stone has only one liberty left. Capture it.',
  },
  b4: {
    title: 'Save your stone',
    prompt: 'Your marked stone is in atari. Give it more liberties.',
  },
  s1: {
    title: 'Back toward the center',
    prompt: 'Your marked stone is in atari: it has only one liberty left. Save it.',
    explanation: 'Yes! By extending to E2, your stones have 3 liberties: D2, F2 and E3. A stone in atari (only one liberty) can often be saved by extending toward the center, where there is room.',
    refutation: 'Not yet. Your stone has only one liberty, at E2: if White plays there, it captures your stone. Take that point yourself.',
  },
  a06: {
    title: 'A group of three',
    prompt: 'Capture the group of three white stones right now.',
    explanation: 'Well done! You capture a group just like a single stone: fill all its liberties, the empty points next to it. Only E4 was left: it was in atari. You take three stones at once.',
    refutation: 'Not yet. The three white stones form one group. Look all around it: only one empty point is still next to it.',
  },
  e03: {
    title: 'Take the one squeezing you',
    prompt: 'Your marked stone is in atari. Capture the marked white stone right now.',
    explanation: 'Nice move! Liberties are the empty points next to a stone. The white stone at E7 had only one, E8: it was in atari. By capturing it, your stone at E6 can breathe again: two liberties, E7 and E5.',
    refutation: 'Not that one. Your marked stone is in atari, but the white stone pressing on it from above is too: it has only one empty point left, just above it.',
  },
  n05: {
    title: 'Save the bigger one',
    prompt: 'Two of your groups are in atari. You can only save one: save the marked stones, the bigger group.',
    explanation: 'Well done! D4 extends your two stones: the chain has three liberties, C4, E4 and D3. White may take G2, but it is a single stone. You kept the other two.',
    refutation: 'Not quite. You save G2, but White plays D4 and captures your two marked stones. Save the bigger group first.',
  },
  a16: {
    title: 'Four stones in the corner',
    prompt: 'Capture the white group in the corner right now.',
    explanation: 'Well done! Stones side by side form a group, and it shares its liberties, the empty points next to it. This one had only one left, C1: it was in atari. You capture four stones at once.',
    refutation: 'Not yet. The four white stones in the corner are side by side: they are one group. Look all around it: only one empty point is still next to it.',
  },
  n06: {
    title: 'Two ways in the corner',
    prompt: 'Capture the marked stone in two moves or less.',
    explanation: 'Well done! There were two right answers. At A2, the stone has only one liberty left, B1: if it extends there, its two stones have only A1, and you take them. At B1, it is the same on the other side. In the corner, a stone has few liberties.',
    refutation: "Not quite. The stone has two liberties, A2 and B1. If you don't put it in atari, White extends to B1 and keeps two liberties.",
  },
  a07: {
    title: 'Capture to save yourself',
    prompt: 'Your stones are in danger. Capture the marked white stone right now to save them.',
    explanation: 'Correct! The stone at A1 had only one liberty (an empty point next to it), A2: it was in atari. By capturing it, your stones can breathe: they now have three liberties, A1, A3 and C1. Capturing a stone that squeezes you is often the best defense.',
    refutation: 'Not quite. Your two stones have only two liberties. If you extend to C1, they have only one left and White captures them at A2. Look at the white stone in the corner instead: it is in atari.',
  },
  c1: {
    title: 'Double atari',
    prompt: 'Black to play and capture. One move threatens both marked stones at once.',
    explanation: 'Well done! At E5, you put both stones in atari: each has only one liberty left, a single empty point next to it. This is a double atari. White can save only one, and you take the other on your next move.',
    refutation: 'Not quite. If you put only one stone in atari, White plays E5: it connects its two stones and escapes. Look for the point next to both.',
  },
  e04: {
    title: 'Block the top',
    prompt: 'Capture the two white stones in the corner in two moves.',
    explanation: 'Nice move! The group had two liberties (empty points next to it), A3 and B1. At A3, you block the way out at the top: it is in atari. If it extends to B1, your stone at B2 squeezes it: it still has only one liberty, C1, and you capture it.',
    refutation: 'Not that one. After B1, White extends to A3, upward: its group has two liberties again, A4 and B3, and you can no longer take it in two moves. Block the way out at the top instead.',
  },
  i09: {
    title: 'Ladder to the edge',
    prompt: 'Capture the marked stone in three moves or less.',
    explanation: 'Well done! D2 puts the stone in atari (it has only one liberty left, C1) and pushes it toward the edge. If White extends to C1, you play D1: its two stones again have only one liberty. If it extends to B1, A1 captures all three stones. This is a ladder: each atari pushes White, all the way to the edge.',
    refutation: 'Not quite. If you put the stone in atari at C1, White extends to D2 and has three liberties: it escapes. Put it in atari from the other side, to push it toward the edge.',
  },
  a08: {
    title: 'Out of the box',
    prompt: "Your marked stone can't extend. Capture the marked white stone right now to save it.",
    explanation: "Well done! Liberties are the empty points next to a stone. The white stone at D9 had only one, D8: it was in atari, and you capture it. Your stone at E9 gains a liberty at D9 and keeps F9. At F9, it would have had none: a move that is not allowed, suicide.",
    refutation: 'Not quite. Your marked stone has only one liberty, F9, and extending there would be suicide: your stone would have no empty point left. The white stone at D9, though, is in atari.',
  },
  n07: {
    title: 'Toward the edge',
    prompt: 'Capture the marked stone in two moves or less.',
    explanation: 'Well done! F2 puts the stone in atari: its only liberty is E1, on the edge. If White extends there, its two stones have only one liberty, F1, because your stone at D1 blocks the other side. You capture them at F1.',
    refutation: 'Not quite. At E1, White extends to F2, toward the center, and has three liberties. Put it in atari from the other side, to push it toward the edge.',
  },
  a17: {
    title: 'Escape on the edge',
    prompt: 'Your marked stone is in atari. Capture the marked white stone right now to save it.',
    explanation: 'Nice move! Liberties are the empty points next to a stone. The white stone at A6 had only one, B6: it was in atari, and you capture it. Your stone at A5 can breathe: it now has two liberties, A6 and B5.',
    refutation: 'Not quite. Your marked stone has only one liberty, B5. The white stone at A6, just above, has only one too: take it before White takes yours.',
  },
  a09: {
    title: 'Push toward the edge',
    prompt: 'Put the marked stone in atari from the right side, then capture it.',
    explanation: 'Well spotted! Putting a stone in atari means leaving it only one liberty (an empty point next to it). After F2, White extends to E1, but on the edge it has only two liberties, D1 and F1. You play D1: atari. It extends to F1, and you capture it at G1. The edge is a wall: push your opponent against it.',
    refutation: 'Not that one. After E1, White extends to F2, toward the center: it has three liberties and escapes. Put it in atari from the other side, to push it toward the edge.',
  },
  e05: {
    title: 'Escape to the left',
    prompt: 'Your marked stones are in atari. Capture the marked white stone right now to save them.',
    explanation: "Excellent! Liberties are the empty points next to a group. The white stone at C1 had only one, B1: it was in atari, and you capture it. Your stones at D1 and E1 now have two liberties, C1 and F1. At F1, they would have stayed in atari.",
    refutation: 'Not quite. Your two marked stones have only one liberty, F1. If you extend there, only F2 is left: still in atari. The white stone at C1, though, has only one empty point left.',
  },
  n08: {
    title: 'Toward your stones',
    prompt: 'Capture the marked stone in two moves or less.',
    explanation: 'Well done! E4 puts the stone in atari and pushes it toward your stones at F4 and G5. If White extends to F5, its two stones have only one liberty left, F6. You capture them at F6.',
    refutation: 'Not quite. At F5, White extends to E4 and has two liberties, D4 and E3: it escapes downward. Push it toward your stones instead.',
  },
  a20: {
    title: 'Remove the cut',
    prompt: 'The white stones cut your stones apart. Capture them right now.',
    explanation: 'Correct! The two white stones are side by side: they are a group, with only one liberty (an empty point next to it), D3. It was in atari. At D3, you capture it, and your stones on the left and right are no longer cut apart.',
    refutation: 'Not yet. The two white stones cut your stones in two. They form one group, and it has only one empty point left, above it.',
  },
  n09: {
    title: 'Two stones against your wall',
    prompt: 'Capture the marked stones in two moves or less.',
    explanation: 'Well done! E4 puts both stones in atari: their only liberty is F4. If White extends there, its three stones have only one liberty left, F3, because your stone at G4 closes the right side. You capture them at F3.',
    refutation: 'Not quite. At F4, White extends to E4 and has two liberties, D4 and E3: it escapes to the left. Push it toward your stone at G4 instead.',
  },
  a18: {
    title: 'Connect and capture',
    prompt: 'One move connects your stones and captures right now.',
    explanation: 'Superb! Liberties are the empty points next to a stone. The white stones at E6 and E4 had only one each, the same one: E5. They were in atari. At E5, you capture them both and connect your stones at D5 and F5.',
    refutation: 'Not yet. Look at the empty point in the middle: it is the last liberty of both white stones, and it connects your stones at D5 and F5.',
  },
  b3: {
    title: 'Double atari',
    prompt: 'One move can put both marked stones in atari at the same time.',
  },
  m01: {
    title: 'Three in a row',
    prompt: 'Black to play and live. Your group has three empty points in a row on the edge.',
    explanation: 'Well done! E1 splits your space into two eyes, D1 and F1. An eye is an empty point surrounded by your stones, where White cannot play: it would be suicide. With two eyes, your group is alive forever. Remember: three in a row, play the middle.',
    refutation: 'Not quite. White plays E1, in the middle of your space: you have only one eye left, and your group ends up captured.',
  },
  n10: {
    title: 'Cut it off from its friend',
    prompt: 'Capture the marked stone in two moves or less.',
    explanation: 'Well done! F5 puts the stone in atari and cuts it off from G5. Its only liberty is E4. If White extends there, its two stones have only one liberty, F4: your stones at D4 and E3 close the rest. You capture them at F4.',
    refutation: 'Not quite. At E4, White plays F5: its stone joins G5, and the group has five liberties. Cut the way to G5 first.',
  },
  s2: {
    title: 'Connect your stones',
    prompt: 'White threatens to cut at E5 and put both your stones in atari at once. Connect them.',
    explanation: "That's it! At E5, your three stones form a single group, with 3 liberties: D4, E4 and F4. Otherwise, White would cut at E5 and play a double atari: two stones in atari (only one liberty) at the same time.",
    refutation: 'Not quite. White can cut at E5: your two stones are split and must each defend on their own. The right point is the one White wants.',
  },
  a10: {
    title: 'Toward your stones',
    prompt: 'Put the marked stone in atari by pushing it toward your stones, and capture it.',
    explanation: 'Excellent! The stone had two liberties (empty points next to it), E4 and F5. After E4, it is in atari: only F5 is left. If White extends to F5, your stones at F6 and G5 are waiting: it still has only one liberty, F4, and you capture it.',
    refutation: 'Not that one. After F5, White extends to E4, downward: it has three liberties and escapes. Push it toward your stones at F6 and G5 instead.',
  },
  e06: {
    title: 'Toward your two stones',
    prompt: 'Put the marked stone in atari by pushing it toward your stones, then capture it.',
    explanation: 'Well done! Putting a stone in atari means leaving it only one liberty (an empty point next to it). After E3, only F4 is left. If White extends there, your stones at F3 and G4 are waiting: its group still has only one liberty, F5, and you capture it.',
    refutation: 'Not that one. After F4, White extends to E3, downward: it gets two liberties back, D3 and E2, and you can no longer capture it in time. Push it toward your stones at F3 and G4.',
  },
  n11: {
    title: 'The corner closes',
    prompt: 'Capture the marked stone in two moves or less.',
    explanation: 'Well done! J8 puts the stone in atari: its only liberty is H9. If White extends there, its two stones have only J9 left, in the corner. You capture them at J9.',
    refutation: 'Not quite. At H9, White extends to J8 and has two liberties, J9 and J7. Put it in atari from the right edge.',
  },
  a19: {
    title: 'Out of the corner',
    prompt: 'Your stones in the corner are in atari. Capture the marked white stone right now to save them.',
    explanation: 'Well done! Liberties are the empty points next to a group. The white stone at G9 had only one, G8: it was in atari, and you capture it. Your corner stones gain a liberty at G9 and keep J8: they have two. At J8, they would have stayed in atari.',
    refutation: 'Not quite. Your two corner stones have only one liberty, J8. If you extend there, they still have only one, J7, and White captures them. The white stone at G9, though, is in atari.',
  },
  a11: {
    title: 'Double atari on the edge',
    prompt: 'One move threatens both marked stones. Find it, then capture.',
    explanation: 'Well done! At D2, you put both stones in atari at once: each has only one liberty left (an empty point next to it), C1 for one, E1 for the other. This is a double atari. White can save only one; you capture the other on your next move.',
    refutation: 'Not quite. If you put only one stone in atari, White plays D2: it connects its two stones and escapes. Look for the point next to both.',
  },
  e07: {
    title: 'The right side of the edge',
    prompt: 'Capture the three white stones on the edge in two moves.',
    explanation: 'Correct! The group had two liberties (empty points next to it), E2 and F1. After F1, it is in atari: only one liberty, E2. If it extends to E2, your stone at E3 blocks it: it still has only one liberty, F2, and you take four stones.',
    refutation: 'Not that one. After E2, White extends to F1, along the edge: it has two liberties again, F2 and G1, and you can no longer take it in two moves. Put it in atari from the other side, toward your stone at E3.',
  },
  n12: {
    title: 'Two stones against the edge',
    prompt: 'Capture the marked stones in two moves or less.',
    explanation: 'Well done! H3 puts both stones in atari: their only liberty is J4, on the edge. If White extends there, its three stones have only one liberty left, J3. You capture them at J3.',
    refutation: 'Not quite. At J4, White extends to H3 and has three liberties, G3, H2 and J3. Put it in atari from below, to push it toward the edge.',
  },
  m02: {
    title: 'The middle of three',
    prompt: 'Black to play and kill. The white group has three empty points in a row on the left edge.',
    explanation: "Correct! At A5, you stop White from making two eyes (two empty points surrounded by its stones). Its space is too small to live: whatever it does, its group ends up captured. The middle point is the vital point: the key point for both players.",
    refutation: 'Not quite. White plays A5, in the middle: it makes two eyes, A6 and A4, and its group is alive.',
  },
  v1: {
    title: 'Two eyes',
    prompt: 'Black to play and live. Your group must make two eyes.',
    explanation: "Perfect! B1 splits your space into two eyes, A1 and C1. An eye is an empty point surrounded by your stones. White can't play in either one: it would be suicide. Your group can never be captured: it is alive.",
    refutation: 'Not quite. After this move, White can play B1, in the middle of your space: you have only one eye left, and your group ends up captured. The key point is the same for both players.',
  },
  a12: {
    title: 'Push toward the corner',
    prompt: 'Put the marked stone in atari from the right side, then capture it.',
    explanation: 'Correct! After B2, the stone is in atari: only one liberty (empty point next to it), C1. If White extends to C1, it has only two liberties, B1 and D1. You play D1, it extends to B1, and you capture it at A1. The corner is where a stone has the fewest liberties.',
    refutation: 'Not that one. After C1, White extends to B2, outward: it has three liberties and escapes. Push it toward the corner.',
  },
  e08: {
    title: 'Two liberties on the edge',
    prompt: 'Capture the two white stones on the edge in two moves.',
    explanation: 'Correct! The group had two liberties (empty points next to it), E2 and F1. You take one: it is in atari. If it extends, your stones at D2 and F2 block the way: it stays in atari and you capture it. Both ataris work.',
    refutation: 'Not yet. The white group has two liberties, E2 and F1. Take one away right now: your stones at D2 and F2 do the rest.',
  },
  n13: {
    title: "Don't put yourself in atari",
    prompt: 'Your marked stone is in atari. Save it.',
    explanation: "Well done! The white stone at C9 is in atari too: B9 captures it. Your stone now has two liberties, C9 and E9. White can't play at C9: its stone would have no liberty there. And if it plays E9, you connect at C9. At E9, you would have put yourself in atari.",
    refutation: 'Not quite. If you extend to E9, your two stones have only one liberty, F9: you put yourself in atari, and White takes them. Anywhere else, White takes your stone at E9. Look at the stone at C9 instead.',
  },
  e09: {
    title: 'On the top edge',
    prompt: 'Capture the two white stones on the edge in two moves.',
    explanation: 'Well done! The group had two liberties (empty points next to it), F8 and G9. After G9, it is in atari: only F8 is left. If it extends there, your stone at F7 blocks the way: only one liberty, G8, and you capture it.',
    refutation: 'Not that one. After F8, White extends to G9, along the edge: it has two liberties again, G8 and H9, and you can no longer take it in two moves. Push it toward your stone at F7.',
  },
  i10: {
    title: 'Close both exits',
    prompt: 'Capture the marked stone in three moves or less.',
    explanation: "Superb! D4 doesn't touch the stone, but it closes both its exits, C4 and D3: this is a net (geta in Japanese). If White comes out at C4, you play C5; if it comes out at D3, you play E3. Each time, its stones have only one liberty left, and you capture them on the next move.",
    refutation: 'Not quite. If you put the stone in atari right away, White extends on the other side and gets two liberties back. Close both its exits with a single move instead.',
  },
  n14: {
    title: 'Capture to save',
    prompt: 'Your marked stone is in atari. Save it.',
    explanation: "Well done! The white stone at B5 is in atari: B4 captures it. Your stone now has two liberties, A4 and B5, and White can't play at B5: it would have no liberty there. If it plays A4, you connect at B5. Extending to A4, along the edge, gave only two liberties.",
    refutation: 'Not quite. At A4, your two stones have only two liberties: White plays B4 and they are in atari again, against the edge. Anywhere else, White takes your stone at A4. Look at the stone at B5 instead.',
  },
  a13: {
    title: 'The shared point',
    prompt: 'The two marked stones share an empty point. Play the double atari, then capture.',
    explanation: 'Nice move! Each stone had two liberties (empty points next to it), and C3 was shared. At C3, you put both in atari at once: this is a double atari. White saves one, you take the other.',
    refutation: 'Not quite. If you threaten only one stone, White plays C3: it connects its two stones and gives them enough liberties. Look for the shared point.',
  },
  d01: {
    title: 'Connect to your strong group',
    prompt: 'Your two marked stones have only two liberties. Connect them to your group.',
    explanation: "Well done! At D4, your marked stones join your big group and share all its liberties (the empty points next to a group). If you had played D3, they would have had only one liberty, D4: White would capture them.",
    refutation: 'Not quite. White plays D4: your two stones have only one liberty left, D3. If you take the stone at D4 by playing D3, White plays D4 again and captures your three stones. Connect on the side of your strong stones.',
  },
  e10: {
    title: 'Double atari in the center',
    prompt: 'One move puts both marked stones in atari. Play it, then capture.',
    explanation: 'Well done! Each white stone had two liberties (empty points next to it), and D6 was shared. At D6, each has only one left, C5 and E5: this is a double atari. White saves one, you take the other.',
    refutation: 'Not quite. If you threaten only one stone, White plays D6: it connects its two stones and gives them enough liberties. Play that point first.',
  },
  k01: {
    title: 'Along the edge',
    prompt: 'Black to play and capture the marked white stones. Keep them pressed against the edge.',
    explanation: 'Well done! After E2, the white stones are in atari: they have only one liberty left (an empty point next to them), F1. If White extends to F1, you play F2 and it is in atari again, and so on up to the corner. Putting a fleeing stone back in atari every move is a ladder. Along the edge, it always ends in a capture.',
    refutation: 'Not quite. After F1, White extends to E2, toward the center, and its stones escape. Block the center side instead.',
  },
  n15: {
    title: 'Double atari',
    prompt: 'Capture one of the marked stones in two moves or less.',
    explanation: 'Well done! E5 puts both stones in atari at the same time: D5 has only D4 left, F5 has only F6. This is a double atari. White saves only one, you capture the other.',
    refutation: 'Not quite. If you put only one stone in atari, White plays E5: it connects its two stones and the group has three liberties. Play the point between them.',
  },
  q01: {
    title: 'Make your eye real',
    prompt: 'Black to play and live. You have two eyes, A1 and C1. But is C1 a real eye?',
    explanation: "Well done! D2 connects D1 and E1 to the rest of your group. A1 and C1 are then two real eyes: two empty points surrounded by your stones, where White can't play. With two real eyes, your group is alive: it can never be captured.",
    refutation: 'Not quite. White plays D2: your stones at D1 and E1 have only one liberty left, C1. White can take them, so C1 is a false eye. With only one real eye, your group ends up captured.',
  },
  s4: {
    title: 'Connect on the edge',
    prompt: 'White threatens to cut your two marked stones at D2. Connect them.',
    explanation: 'Correct! At D2, your stones form one group with 4 liberties: C1, D1, E1 and F2. On its own, the stone at C2 had only two (the empty points next to it): cut off, it would have been captured.',
    refutation: 'Not quite. White can cut your stones, and your stone at C2, with few liberties, ends up captured. The cutting point is also your connecting point.',
  },
  v3: {
    title: 'Only one eye',
    prompt: 'Black to play and kill. Stop the white group from making two eyes.',
    explanation: "Correct! At E9, in the middle, you stop White from making two eyes (two empty points surrounded by its stones). With only one eye, its group can't live: whatever it does, it ends up captured.",
    refutation: 'Not quite. White plays E9 and makes two eyes, D9 and F9: its group is alive forever.',
  },
  j01: {
    title: 'The cut that threatens twice',
    prompt: 'Capture one of the marked stones in two moves or less.',
    explanation: 'Well done! C2 cuts the two white stones apart. Each has only one liberty left: B1 for B2, E2 for D2. They are both in atari (only one liberty). This is a double atari: White saves only one, you take the other.',
    refutation: 'Not quite. If you put only one stone in atari, White connects its two stones at C2 and gets two liberties back. Play the point that splits them instead.',
  },
  e11: {
    title: 'Against the left edge',
    prompt: 'Put the marked stone in atari from the right side, then capture it.',
    explanation: "Correct! After B3, the stone has only one liberty left (an empty point next to it), A4: it is in atari. If White extends to A4, its group has only two liberties on the edge, A3 and A5. You take one, it extends, and you capture it on the next move. The edge leaves no room to run.",
    refutation: 'Not that one. After A4, White extends to B3, inward: it has three liberties and escapes. Push it against the edge instead.',
  },
  n16: {
    title: 'Not the easiest one',
    prompt: 'Capture the marked stone in two moves or less.',
    explanation: 'Well done! E3 puts E2 in atari from above: its only liberty is E1. If White extends there, it connects to D1, but its three stones have only one liberty, F1. You capture them at F1. Taking D1 at E1 was easier, but E2 would escape.',
    refutation: 'Not quite. At E1, you take D1, but White extends to E3, toward the center, and has three liberties. The stone that matters is E2.',
  },
  a14: {
    title: 'Who has more liberties?',
    prompt: 'Your marked group and the marked white group squeeze each other. Capture the white group in two moves.',
    explanation: 'Well done! Liberties are the empty points next to a group. Your group had two, and so did the white group: whoever plays first wins. After C7, the white group is in atari (only one liberty, D7). If it extends to D7, it stays in atari; if it attacks your group, you capture it at D7 first.',
    refutation: 'Not the fastest. Count the liberties: your marked group has two, A7 and B7, and so does the white group, C7 and D7. Whoever plays first wins: take a liberty from the white group right now.',
  },
  b2: {
    title: 'Toward the edge',
    prompt: "Put the marked stone in atari from the right side so it can't escape.",
  },
  d02: {
    title: 'Save the cutting stones',
    prompt: 'Your two marked stones cut White in two. They are in atari: save them.',
    explanation: 'Correct! Your two stones are cutting stones: they split White into two groups. They were in atari (only one liberty). At E3, they have 3 liberties: D3, E2 and F3. The two white groups stay apart, and White is the one who must defend.',
    refutation: 'Not yet. Your stones have only one liberty, E3: White plays there and captures them, and its two groups are no longer cut. Take that point yourself.',
  },
  k02: {
    title: 'Close the open side',
    prompt: 'Black to play and capture the two marked white stones on the edge.',
    explanation: 'Nice move! The white stones have three liberties (the empty points next to them): D1, F1 and F2. At F2, you close the only side that leads to open space. They have only two liberties left on the first line, and each time White extends along the edge, you put it back in atari (only one liberty) until you capture it.',
    refutation: 'Not quite. If you block from the left, White extends to F2, toward open space, and its stones escape. Close the open side first.',
  },
  m03: {
    title: 'The bent three on the edge',
    prompt: 'Black to play and live. Three empty points in a bent shape: find the vital point.',
    explanation: "Nice move! E1 touches the two other empty points: it is the vital point, the key point for both players. It leaves you two eyes, D1 and E2. An eye is an empty point surrounded by your stones, where White can't play. Your group is alive.",
    refutation: 'Not quite. White plays E1, the point that touches the two others: you have only one eye left and your group ends up captured.',
  },
  o01: {
    title: 'The net',
    prompt: 'Capture the marked stone in three moves or less.',
    explanation: "Well done! E6 doesn't touch the stone, but it closes both its exits, D6 and E5: this is a net (geta in Japanese). If White comes out at D6, you play C6: it is in atari (only one liberty). If it extends to E5, it still is, and you take it at E4. If it comes out at E5 first, you play E4, then C6.",
    refutation: "Not quite. White extends to E5, or to D6 if you played E5 or E4, and keeps enough liberties to escape. Don't touch the stone: close both its exits.",
  },
  s3: {
    title: 'Take the cutting stone',
    prompt: 'Your marked stone is in atari. The white stone cutting it is in atari too.',
    explanation: 'Well done! At E6, you capture the white stone at E5. Your stone gets liberties back (the empty points next to it) and, if White puts it in atari again at D6, you connect at E5. Capturing the cutting stone is often the best way to save yourself.',
    refutation: 'Not quite. If you extend to D6, White answers E6: its cutting stone is saved and yours stays in danger. Capture the cutting stone first.',
  },
  g01: {
    title: 'Close the cut',
    prompt: 'White threatens to cut your two groups apart. Connect them.',
    explanation: 'Well done! D3 is the cutting point: if White plays there, it splits your two groups. Cutting means playing between two enemy groups to split them. At D3, your stones form a single group, with enough liberties to hold. When your opponent threatens to cut, connect first.',
    refutation: 'Not quite. White plays D3 and cuts your two groups apart: on its own, each one no longer has enough liberties. Connect them first.',
  },
  j02: {
    title: 'Snapback in the corner',
    prompt: 'Capture the marked stone in two moves or less.',
    explanation: 'Superb! At B1, your stone has only one liberty, B2: White can take it. But A2 and A1 are in atari (only one liberty). If White takes at B2, its three stones have only one liberty left, B1. You play B1 again and capture them all. This is a snapback: you give one stone to take three.',
    refutation: 'Not quite. At B2, you put the stones in atari, but White plays B1: it connects them to its stones below and gets three liberties back. Play B1 instead, even if White can take your stone.',
  },
  n17: {
    title: 'The right stone to take',
    prompt: 'Your marked stone is in atari. Save it.',
    explanation: 'Well done! The white stone at F2 is in atari: F1 captures it, and your stone can breathe. E1 works too: your two stones have two liberties, D1 and F1, and F2 stays in atari. If White plays D1, you take F2 at F1. The two stones at A8 and B8 are worth less than your stone.',
    refutation: 'Not quite. You take two stones at A9, but White plays E1 and captures your stone. The stone to take is the one putting you in atari.',
  },
  p01: {
    title: 'Against your wall',
    prompt: 'Capture the marked stones in two moves or less.',
    explanation: 'Well done! The marked stones have two liberties, E5 and F4. Play on one of them: the stones are in atari (only one liberty). If White extends to the other, it runs into your stones at F5 and G4: it is still in atari, and you take it.',
    refutation: 'Not quite. White extends to E5, or to F4 if you played E6, and keeps two liberties. Put it in atari right away, on the side of your stones.',
  },
  e12: {
    title: 'Close the way out',
    prompt: 'Capture the two white stones in three moves or less.',
    explanation: 'Superb! The group had three liberties (empty points next to it), D1, E1 and F2. At F2, you close the only way out toward the center. Only D1 and E1 are left, on the edge: if it extends, each time you put it back in atari (only one liberty), until you capture it.',
    refutation: 'Not yet. The white group has three liberties: D1, E1 and F2. Only F2 leads toward the center: close it first, and the edge does the rest.',
  },
  o02: {
    title: 'Give one stone, take three',
    prompt: 'Capture the marked stones in two moves or less.',
    explanation: 'Well done! At E1, your stone has only one liberty, E2: White can take it. But its stones at D2 and D1 have only one liberty too, E2: they are in atari. If it takes at E2, its three stones have only one liberty left, E1. You play E1 again and capture them. This is a snapback: you give one stone to take three.',
    refutation: 'Not quite. At E2, you put the stones in atari, but White plays E1: it connects them to its stones at F1, G1 and H1, and the group can breathe. Play E1 instead, even if White can take your stone.',
  },
  n18: {
    title: 'Take the cutting stone',
    prompt: 'Your two marked stones are in atari. Save them both.',
    explanation: "Well done! The white stone at C2 cuts your two stones apart, and it is in atari: C1 captures it. Each of your stones now has two liberties. White can't play at C2: its stone would have no liberty there. If it attacks, you connect at C2. J5 and J6 are two stones, but the cutting stone is worth more.",
    refutation: 'Not quite. White plays C1: it saves its cutting stone, and your two stones stay in atari. You save only one, and it takes the other.',
  },
  d03: {
    title: 'The right cutting point',
    prompt: 'The two marked white stones want to connect to the white group on the right. Cut them off and capture them.',
    explanation: 'Well done! Cutting means playing between two enemy groups to stop them from connecting. E2 is the cutting point: the marked stones have only one liberty left, D1. If White extends to D1, you play E1 and capture three stones.',
    refutation: 'Not quite. After this move, White plays E2 and connects its marked stones to its group on the right: they are saved. Cut at the connecting point.',
  },
  f01: {
    title: 'Save your cutting stones',
    prompt: 'Your two marked stones cut White apart, but they are in atari. Save them.',
    explanation: 'Well done! Your marked stones are cutting stones: they split the white stones apart. They are in atari (only one liberty, B5), but so are the two white stones D6-D5: their only liberty is D4. At D4, you capture them, and your stones get liberties back. B5 works too: your stones then have two liberties, and if White attacks them, you take D6-D5 at D4.',
    refutation: 'Not quite. Your marked stones have only one liberty, B5: White plays there and captures them. Look at the white stones touching them too: they are in atari as well.',
  },
  g02: {
    title: 'Connect by capturing',
    prompt: 'The white stone at D2 splits your two groups. Connect them.',
    explanation: "Correct! The stone at D2 cuts your two groups apart, but it is in atari: it has only one liberty left, D1. At D1, you capture it: the point D2 becomes yours, White can't play there anymore, and your groups are connected. C1 and E1 work too: if White extends to D1, it stays in atari and you take it on the next move. But D1 is the simplest.",
    refutation: 'Not quite. White extends to D1: its cutting stone gets liberties back, and your two bottom groups stay apart and in danger. Deal with the stone at D2.',
  },
  j03: {
    title: 'The trap on the edge',
    prompt: 'Capture the marked stone in two moves or less.',
    explanation: 'Well done! At E1, your stone has only one liberty, F1, and White can take it. But E2 and F2 are in atari (only one liberty). If White takes at F1, its three stones have only one liberty left, E1: you play E1 again and capture them. This is a snapback. And E1 stops White from connecting to C1 and D1.',
    refutation: 'Not quite. At F1, White plays E1: it connects its stones to C1 and D1, and the group has two liberties, B1 and C2. Play E1 instead, even if White can take your stone.',
  },
  k03: {
    title: 'The ladder',
    prompt: 'Black to play and capture the marked stone. No white stone can come to help it.',
    explanation: 'Correct! You put the stone in atari (only one liberty). Each time it extends, you put it back in atari from the same side: it zigzags diagonally to the edge, where it is captured. This is a ladder. Here, both ataris work, because no white stone is waiting on the way.',
    refutation: "Not yet. The marked stone has two liberties, E6 and D5. If you don't put it in atari right away, White plays on one of them and escapes toward the center.",
  },
  m04: {
    title: 'Kill the bent three',
    prompt: 'Black to play and kill. The white group has three empty points in a bent shape.',
    explanation: "Well done! F9 is the vital point of the bent three: the point that touches the two others. White can no longer make two eyes (two empty points surrounded by its stones). Whatever it does, its group ends up captured.",
    refutation: 'Not quite. White plays F9, the corner of the bend: it makes two eyes, E9 and F8, and its group is alive.',
  },
  o03: {
    title: 'Count the liberties',
    prompt: 'Capture the marked stones in three moves or less.',
    explanation: 'Well done! Your stones at A2, B2 and C2 and the marked stones are shut in side by side. Each group has three liberties: A1, B1 and C1 for you, D1, E1 and F1 for White. Whoever fills all the other side\'s liberties first wins: this is a capturing race (semeai in Japanese). You play first: you win by one move, if you fill White\'s liberties and never your own.',
    refutation: "Not quite. White plays C1, or B1 if you played C1, and fills one of your liberties. You then have fewer liberties than White, and White wins the race. Fill White's liberties, not your own.",
  },
  q02: {
    title: 'Make the eye false',
    prompt: 'Black to play and kill. White has two eyes, C1 and E1. Look at the corners of E1.',
    explanation: "Well done! F2 touches E1 diagonally. The stones at F1 and G1 have only one liberty left, E1: you can take them. So E1 is a false eye: it doesn't count. White has only one real eye, C1 (an empty point surrounded by its stones), and its group ends up captured.",
    refutation: 'Not quite. White plays F2 and connects F1 and G1 to its group. C1 and E1 are then two real eyes: the white group is alive and can never be captured.',
  },
  v2: {
    title: 'Bent three in the corner',
    prompt: 'Black to play and live. Three empty points in a bent shape: where is the key point?',
    explanation: "Nice move! At A1, you get two eyes, A2 and B1. An eye is an empty point surrounded by your stones. White can't play in either one: it would be suicide. Your group is alive.",
    refutation: 'Not quite. After this move, White can stop you from making two eyes and your group ends up captured. Look for the point that splits the space in two.',
  },
  o04: {
    title: 'Close both exits',
    prompt: 'Capture the marked stone in three moves or less.',
    explanation: 'Well done! D5 closes both exits of the stone, D4 and E5, without touching it: this is a net (geta). If White comes out at D4, you play D3: it is in atari, and if it extends to E5, you take it at F5. If it comes out at E5, you play F5, then D3.',
    refutation: 'Not quite. White extends to E5, or to D4 if you played E5 or F5, and keeps enough liberties to escape. Close both its exits first, without touching the stone.',
  },
  d04: {
    title: 'Cut on the edge',
    prompt: 'The three marked white stones want to join the white wall on the right. Cut them off and capture them.',
    explanation: 'Nice move! Cutting means playing between two enemy groups to split them. F8 cuts the marked stones off from the white wall: they have only one liberty left, E9. If White extends to E9, you play F9 and capture four stones.',
    refutation: 'Not quite. After this move, White plays F8 and connects its marked stones to the white wall: they are saved. Cut at the connecting point.',
  },
  e13: {
    title: 'Shut it in toward the corner',
    prompt: 'Capture the two white stones in three moves or less.',
    explanation: 'Superb! The group had three liberties (empty points next to it): B2, C2 and D3. D3 closes the only way out to open space. Only B2 and C2 are left, toward the corner, where your stones at A2, B1 and C1 are waiting. If it extends, you put it back in atari (only one liberty), then capture it.',
    refutation: 'Not yet. The white group has three liberties: B2, C2 and D3. Toward the corner, your stones are already waiting; only one liberty leads to open space. Close it first.',
  },
  f02: {
    title: 'Two against two, one way out',
    prompt: 'Capturing race: your group G6-G9 against the marked white group. Each has 2 liberties.',
    explanation: 'Correct! In a capturing race (semeai), two groups surround each other and whoever takes all the other\'s liberties first wins. White has 2 liberties, J9 and H5; so do you, F7 and F6. But H5 is a way out: by playing there, White would connect to the white wall at G5. After H5, White is in atari (only one liberty) and you capture it at J9 on the next move.',
    refutation: 'Not quite. White plays H5 and connects its group to the white wall at G5: it leaves the capturing race. Block the way out first.',
  },
  h01: {
    title: 'Save by connecting',
    prompt: 'Your stone at E3 is in atari. Save it by connecting it to your stones.',
    explanation: 'Well done! E3 has only one liberty, E2. At E2, you connect it to D2: the group gains liberties at C2 and D1. If White cuts at C2, its stone has only one liberty left, C1: you capture it and everything stays connected. A stone in atari can often be saved by connecting it.',
    refutation: 'Not quite. Your stone at E3 is in atari: its only liberty is E2. If you play elsewhere, White plays there and captures it. Connect it first.',
  },
  p02: {
    title: 'Two ataris in one move',
    prompt: 'Capture a marked stone in two moves or less.',
    explanation: 'Well done! E2 goes between the two stones and puts them both in atari: this is a double atari. White can save only one. If it extends to D1, you take F2 at F1. If it extends to F1, you take D2 at D1.',
    refutation: 'Not quite. White plays E2: it connects its two stones, and the group has four liberties. Play the point that touches both stones at once.',
  },
  f03: {
    title: 'Cut on the first line',
    prompt: 'Black to play and capture the two marked white stones. They have two liberties: A1 and D1.',
    explanation: "Well done! D1 cuts the marked stones off from the white group on the right: cutting means playing between two enemy groups to split them. Their last liberty, A1, is in the corner, next to your stone at A2: White can't extend there, it would be suicide. You capture them on the next move.",
    refutation: 'Not quite. After A1, White plays D1 and connects its marked stones to the white group on the right: they are saved. Cut at the connecting point.',
  },
  e14: {
    title: 'The lid',
    prompt: 'Capture the two white stones on the edge in three moves or less.',
    explanation: 'Well done! The group had three liberties (empty points next to it): A1, C1 and B3. B3 puts a lid on it: only A1 and C1 are left, on the first line. If it extends to C1, you play D1 and it is in atari (only one liberty); if it plays A1, you capture it at C1.',
    refutation: "Not yet. The white group has three liberties: A1, C1 and B3. On the first line, it goes nowhere; only one liberty leads upward. Close it first.",
  },
  f04: {
    title: 'Cut on the right edge',
    prompt: 'Black to play and capture the three marked white stones. They have two liberties: J6 and J2.',
    explanation: "Nice move! J6 cuts the marked stones off from the white group above: cutting means playing between two enemy groups to split them. Their last liberty, J2, is surrounded by your stones at H2 and J1: White can't extend there, it would be suicide. You capture them on the next move.",
    refutation: 'Not quite. After this move, White plays J6 and connects its marked stones to the white group above: they are saved. Cut at the connecting point.',
  },
  o05: {
    title: 'Snapback on the edge',
    prompt: 'Capture the marked stones in two moves or less.',
    explanation: 'Superb! At A5, your stone has only one liberty, B5. White can take it, but its two marked stones are in atari. If it takes at B5, its three stones have only one liberty left, A5. You play A5 again and capture them. This is a snapback.',
    refutation: 'Not quite. At B5, you put the stones in atari, but White plays A5: it connects them to its stones above, and the group has three liberties. Play A5 instead, even if White can take your stone.',
  },
  b5: {
    title: 'Capture to save yourself',
    prompt: "Your marked stone is in atari, and extending isn't enough.",
  },
  c4: {
    title: 'The snapback',
    prompt: 'Black to play and capture. The marked group has only two liberties, and White threatens to connect at C1.',
    explanation: "Superb! Your stone at C1 can be taken, but if White captures it at B1, its group has only one liberty left: C1. You play there again right away and take 5 stones. This is a snapback: you sacrifice one stone to take more. It is not a ko, because you take back several stones, not just one.",
    refutation: 'Not quite. After B1, White takes your stone at C1 and connects to its stones at D1 and E1: it escapes. Sacrifice your stone instead, at the point that also touches those stones.',
  },
  d05: {
    title: 'First one there',
    prompt: 'Your group C1-C4 and the marked white group surround each other. Count their liberties and win the race.',
    explanation: "Well spotted! This is a capturing race (semeai in Japanese): two groups surround each other, neither can live on its own, and whoever takes all the other's liberties first wins. Here, 2 against 2: whoever plays first wins. At A2, White has only A1 left and you capture it on the next move. A1 works too: if White takes your stone at A2, its group still has only one liberty, A1, and you take it.",
    refutation: "Not quite. White takes one of your liberties at D2: your group C1-C4 has only one left, D1, and White captures it before you take White's. Attack White's liberties first.",
  },
  e15: {
    title: 'No way out',
    prompt: 'Capture the two white stones on the edge in three moves or less.',
    explanation: 'Superb! The group had three liberties (empty points next to it): C1, E1 and D3. D3 closes the way out toward the center. If it extends to E1, you play F1: it is in atari (only one liberty), and you capture it at B1 if it goes on to C1. Push it toward your stones, not toward open space.',
    refutation: "Not yet. The white group has three liberties: C1, E1 and D3. On the first line, it can't get far; the only way out toward the center is D3. Close it first.",
  },
  f05: {
    title: 'The right side',
    prompt: 'Black to play and capture the marked white stones. They have two liberties: which one do you take?',
    explanation: "Well spotted! C2 cuts the marked stones off from the white stone at B2 and puts them in atari (only one liberty). Their last liberty, E2, is surrounded by your stones at E3, F2 and E1: White can't extend there, it would be suicide. On top of that, C2 connects your stones B1-C1 and puts B2 in atari.",
    refutation: 'Not quite. After E2, White extends to C2: it connects to its stone at B2 and also puts your stones B1-C1 in atari. Put it in atari from the other side.',
  },
  g03: {
    title: 'One stone saves everything',
    prompt: 'Your left group is in atari and your right group is weak. One move saves both.',
    explanation: "Superb! Your left group is in atari: it has only one liberty, C1. But the white stone at D2, which splits your two groups, is in atari too: its only liberty is D1. At D1, you capture it. Your left group gets a liberty back at D2, White can't play there anymore, and your two groups are connected. Capturing the cutting stone saves everything at once.",
    refutation: "Not quite. Your left group is in atari: its only liberty is C1. If you don't deal with it right away, White plays there and captures it. Look for the move that saves both groups.",
  },
  k04: {
    title: 'Shortage of liberties',
    prompt: 'Black to play and capture the white group. White wants to make two eyes on the edge.',
    explanation: "Well done! At B1, you stop White from making two eyes (two empty points surrounded by its stones). And White can't take your stone: to put it in atari at A1 or C1, it fills one of its own last two liberties and puts itself in atari. You then capture the whole group. Being unable to attack without losing your own liberties is a shortage of liberties (damezumari in Japanese).",
    refutation: 'Not quite. White plays B1 and makes two eyes, A1 and C1: its group is alive. The key point is the same for both players.',
  },
  m05: {
    title: 'The bent three in the corner',
    prompt: 'Black to play and kill. The white group has three empty points in a bent shape, in the corner.',
    explanation: 'Correct! A1 touches the two other empty points: it is the vital point, the key point for both players. White can no longer make two eyes (two empty points surrounded by its stones). Whatever it does, its group ends up captured.',
    refutation: 'Not quite. White plays A1, the corner: it makes two eyes, A2 and B1, and its group is alive.',
  },
  f06: {
    title: 'Cut in the center',
    prompt: 'Black to play and capture the two marked white stones. They have two liberties: B5 and E5.',
    explanation: "Correct! E5 cuts the marked stones off from the white group on the right: cutting means playing between two enemy groups to split them. Their last liberty, B5, is surrounded by your stones at A5, B6 and B4: White can't extend there, it would be suicide. You capture them on the next move.",
    refutation: 'Not quite. After this move, White plays E5 and connects its marked stones to the white group on the right: they are saved. Cut at the connecting point.',
  },
  j04: {
    title: 'Cut despite the threat',
    prompt: 'Capture one of the marked stones in two moves or less.',
    explanation: 'Superb! D2 cuts and puts both groups in atari (only one liberty): A1 for the left one, E1 for the right one. Your stone at C1 is in atari too. But if White takes it at D1, the right group stays in atari: you capture it at E1.',
    refutation: 'Not quite. If you put only one group in atari, White plays D2: it connects its two groups, and they can breathe. Cut at D2 first.',
  },
  o06: {
    title: 'The net, no touching',
    prompt: 'Capture the marked stone in three moves or less.',
    explanation: 'Well done! G5 closes both exits of the stone, F5 and G4: this is a net. If White comes out at F5, you play E5: it is in atari, and if it extends to G4, you take it at H4. If it comes out at G4, you play H4, then E5.',
    refutation: "Not quite. White extends to G4, or to F5 if you played G4 or H4, and keeps enough liberties to escape. Don't touch the stone: close both its exits.",
  },
  f07: {
    title: 'Cut at the edge',
    prompt: 'Black to play and capture the two marked white stones. They have two liberties: E9 and D7.',
    explanation: "Well done! E9 cuts the marked stones off from the white group on the right: cutting means playing between two enemy groups to split them. They have one liberty left, D7, surrounded by your stones at C7, E7 and D6: White can't extend there, it would be suicide. You capture them on the next move.",
    refutation: 'Not quite. After this move, White plays E9 and connects its marked stones to its group on the right: they are saved. Cut at the connecting point.',
  },
  g04: {
    title: 'The cutting point',
    prompt: 'Your small group on the right is weak. Connect it to your group on the left.',
    explanation: 'Well done! D3 connects your two groups. If White played there, it would cut: your group E3-E2 would have only one liberty left, E1, and be in atari. Cutting means playing between two enemy groups to split them. Connected, your group has enough liberties to hold.',
    refutation: "Not quite. White plays D3 and cuts: your group E3-E2 has only one liberty left, E1. It is in atari and can't escape. Connect it first.",
  },
  j12: {
    title: 'Capture to connect',
    prompt: 'Capture the marked stone in three moves or less. It cuts your stones in two.',
    explanation: 'Well done! E3 puts the stone in atari (it has only one liberty left, E1) and pushes it toward the edge. If White extends to E1, its two stones have two liberties, D1 and F1. You take one, for example D1: White extends to F1 and has only G1 left. You capture at G1. Your two groups are connected.',
    refutation: 'Not quite. At E1, White extends to E3 and has three liberties: its stone escapes, and your stones stay cut apart. Put it in atari from above, to push it toward the edge.',
  },
  c3: {
    title: 'The net',
    prompt: "Black to play and capture. Putting it in atari right away isn't enough.",
    explanation: "Well spotted! Your move doesn't touch the stone, but it blocks its path: this is a net (geta in Japanese). The tightest net is F4; G4 and F3, a bit looser, work too. After F4, if White comes out at F5, you play G5; if it comes out at E4, you play E3. Each time, it is in atari (only one liberty) and you capture it.",
    refutation: 'Not quite. If you put it in atari right away, White extends and the ladder that follows runs into the white stone at G2: White connects to it and escapes. Play one step farther, diagonally, to shut it in.',
  },
  d06: {
    title: 'Cut before you take',
    prompt: "Black to play and capture the two marked white stones. Taking right away isn't best.",
    explanation: 'Superb! G4 cuts F4 off from the white stone at G3: cutting means playing between two enemy stones to split them. The two marked stones have only one liberty each, F5. If White connects them at F5, its three stones have only one liberty, F6, and you capture them. Otherwise, you play F5 and take both.',
    refutation: 'Not quite. If you take E5 at F5, the stone at F4 has only one liberty left, G4: White plays there, connects to G3 and escapes. Cut F4 off from G3 first.',
  },
  f08: {
    title: 'Three against three, one way out',
    prompt: 'Capturing race: your group C1-C4 and the marked white group have 3 liberties each. Play the winning move.',
    explanation: "Correct! In a capturing race (semeai), two groups surround each other and whoever takes all the other's liberties first wins. White has 3 liberties: A2, A1 and B5. So do you: D4, D3 and D2. But at B5, White would connect to the white wall at C5. Block that way out first: White has only 2 liberties against your 3, and you capture it one move ahead.",
    refutation: 'Not quite. White plays B5 and connects its group to the white wall at C5: it leaves the capturing race and can no longer be captured.',
  },
  j05: {
    title: 'Close it from outside',
    prompt: 'Black to play and kill. The white group has two spaces on the edge: C1-D1 and F1-G1.',
    explanation: "Well done! G1 leans on your stone at H1 and touches F1: F1 is no longer an eye (an empty point surrounded by White). White has only the C1-D1 space left, which makes just one eye. With only one eye, its group ends up captured. At F1, your stone would have had only one liberty: White would have taken it at G1.",
    refutation: 'Not quite. White plays G1: F1 becomes an eye, and C1-D1 makes a second one. Its group is alive.',
  },
  k05: {
    title: 'The broken ladder',
    prompt: 'Black to play and capture the marked stone. Look where each ladder leads before you play.',
    explanation: 'Well spotted! A ladder (a series of ataris zigzagging diagonally) is broken when an enemy stone is in its path: the fleeing stone connects to it and gets liberties back. The white stone at B3 breaks the ladder toward the lower left. With D5, White extends to E6 and runs toward the upper right, where nothing is waiting: it is captured against the edge.',
    refutation: 'Not that one. After E6, White extends to D5 and the ladder heads to the lower left: it runs into the white stone at B3, White connects to it and escapes. Push it the other way.',
  },
  m06: {
    title: 'The stone in your camp',
    prompt: 'Black to play and live. A white stone has come into your space.',
    explanation: "Perfect! E1 puts the white stone at D1 in atari: it has only one liberty left, C1, and White can't play there, it would be suicide. F1 is already an eye (an empty point surrounded by your stones). You capture D1 whenever you like, and its point becomes your second eye. Your group is alive.",
    refutation: 'Not quite. White plays E1 and connects its stone at D1: your space becomes too small, you have only one eye left and your group ends up captured. The right point is right next to the white stone.',
  },
  o07: {
    title: 'Snapback at the top',
    prompt: 'Capture the marked stones in two moves or less.',
    explanation: 'Superb! At G9, your stone has only one liberty, G8. But the marked stones are in atari too. If White takes at G8, its three stones have only one liberty left, G9: you play G9 again and capture them. You give one stone to take three: this is a snapback.',
    refutation: 'Not quite. At G8, you put the stones in atari, but White plays G9: it connects them to its stones on the right, and the group has two liberties, H7 and J6. Play G9 instead, even if White can take your stone.',
  },
  p03: {
    title: 'Give one stone, take five',
    prompt: 'Capture the marked stones in two moves or less.',
    explanation: 'Superb! At E1, your stone has only one liberty, E2. But the four white stones have only one liberty too, E2: they are in atari. If White takes at E2, its five stones have only one liberty, E1. You play E1 again and capture them all. This is a snapback: you give one stone to take five.',
    refutation: 'Not quite. White plays E1: it connects its four stones to F1, G1 and H1, and the group can breathe. Play E1 instead, even if White can take your stone.',
  },
  v4: {
    title: 'Kill in the corner',
    prompt: 'Black to play and kill. The white group has three empty points in a bent shape.',
    explanation: "Well done! J9 is the key point of the bent three. White can no longer make two eyes (two empty points surrounded by its stones): whatever it does, its group ends up captured.",
    refutation: 'Not quite. White plays J9 and makes two eyes, H9 and J8: its group is alive.',
  },
  g05: {
    title: 'Connect first',
    prompt: 'White threatens to cut your marked stones. Connect them.',
    explanation: "Correct! C3 connects D3-E3 to your group on the left. If White played there, it would cut: D3-E3 would have only one liberty left, E2, and be in atari. Don't be distracted by your stones F2-F1: they are in atari, but saving them at E2 only adds stones to a group with one liberty, C3.",
    refutation: 'Not quite. White plays C3 and cuts: your group D3-E3 has only one liberty left, E2, and White captures it on the next move. Connect it first.',
  },
  j06: {
    title: 'The eye touched from above',
    prompt: 'Black to play and kill. White has one eye at B2. Can it make a second one?',
    explanation: 'Well done! D3 leans on your wall and touches D2: D2 is no longer an eye (an empty point surrounded by White). White has only one eye left, at B2. If it fills D2, it still has only one eye, and its group ends up captured.',
    refutation: 'Not quite. White plays D3 and has two eyes, B2 and D2. If you go in at D2, your stone has only one liberty: White takes it at D3.',
  },
  o08: {
    title: 'Toward your stone at H2',
    prompt: 'Capture the marked stone in four moves or less.',
    explanation: 'Well done! E4 puts the stone in atari and pushes it down. If it extends to F3, you play F2; if it then extends to G3, you play H3. White has only one liberty left, G2. If it extends there, your stone at H2 blocks the way: it stays in atari, and you take it at G1. Putting a fleeing stone back in atari every move is a ladder. Your stone at H2 helps: it is called a helper stone.',
    refutation: "Not quite. At F3, White extends to E4, upward, away from your stone at H2: it has two liberties, D4 and E5, and you can no longer take it in four moves. Anywhere else, it also extends to E4. Push it toward H2 instead.",
  },
  b6: {
    title: 'The ladder',
    prompt: 'Put the marked stone in atari so that it can never escape.',
  },
  c2: {
    title: 'The broken ladder',
    prompt: 'Black to play and capture. Watch out for the white stone at C2: only one of the two ataris works.',
    explanation: "Correct! White extends to F5, and you put it back in atari (only one liberty) every move, zigzagging to the upper right: this is a ladder. No white stone is waiting on that path, so it ends up captured against the edge.",
    refutation: 'Not that one. After F5, White extends to E4 and runs toward the lower left: the white stone at C2 breaks the ladder, White connects to it and escapes. Push it the other way.',
  },
  d07: {
    title: 'Three against three',
    prompt: 'Capturing race: your group C1-C4 against the marked white group. Who wins? Play the winning move.',
    explanation: "Correct! In a capturing race (semeai), you count: 3 liberties for White (A3, A2, A1), 3 for you (D3, D2, D1). When it's equal, whoever plays first wins. Each move at A3, A2 or A1 takes a liberty from White. Then, each time White plays on your liberties, you answer on its own, and you capture it one move before it captures you.",
    refutation: "Not quite. Your group C1-C4 and the white group have 3 liberties each. If you don't reduce White's right away, White takes yours (D3, D2, D1) and wins by one move.",
  },
  k06: {
    title: 'Take the cutting stone',
    prompt: 'The marked white stone cuts your stones at D5 and E6. Black to play and capture it.',
    explanation: 'Well done! E4 puts the cutting stone in atari (only one liberty). If it extends to F5, you put it back in atari every move, zigzagging to the lower right: this is a ladder, and no white stone is waiting on that path. Once the cutting stone is captured, your stones at D5 and E6 are firmly connected.',
    refutation: 'Not that one. After F5, the cutting stone extends to E4, toward the center: it has three liberties and escapes. Push it toward your stone at F6 instead.',
  },
  q03: {
    title: 'Five points on the edge',
    prompt: 'Black to play and kill. White has five empty points, from C1 to G1. Your stone at H1 touches G1.',
    explanation: 'Superb! Two moves work. At G1, you shrink the space to four points, and F1 touches your stone: White no longer has room for two eyes (two empty points surrounded by its stones). At D1, you play in the middle of its space and stop it from splitting it into two eyes. Either way, its group ends up captured.',
    refutation: 'Not quite. White plays G1, or D1 if you played E1. It keeps enough room for two eyes: its group is alive. Play G1 or D1 before White does.',
  },
  j07: {
    title: 'Four in a row on the edge',
    prompt: 'Black to play and live. You have five empty points on the first line, from A1 to E1.',
    explanation: 'Well done! E1 blocks White and leaves you four points in a row, from A1 to D1. Four points in a row on the edge make two eyes: if White plays B1, you answer C1, and the other way around. B1 works too: it makes an eye in the corner, at A1. If White then plays D1, you answer E1, and the other way around.',
    refutation: "Not quite. If you play A1 or C1, White plays E1: your space becomes too small for two eyes. If you play D1, White plays B1, and it's the same.",
  },
  o09: {
    title: 'The net under the wall',
    prompt: 'Capture the marked stone in three moves or less.',
    explanation: 'Well done! D5 closes both exits of the stone, D6 and E5: this is a net. If White comes out at D6, you play C6: it is in atari, and if it extends to E5, you take it at F5. If it comes out at E5, you play F5, then C6.',
    refutation: "Not quite. White extends to E5, or to D6 if you played E5 or F5, and keeps enough liberties to escape. Don't touch the stone: close both its exits.",
  },
  j08: {
    title: 'Keep your stone inside',
    prompt: 'Black to play and kill. Your stone at F1 has come into the white camp.',
    explanation: "Well done! Your stone at F1 had only two liberties, E1 and G1. G1 connects it to H1: it is saved. E1 touches F1, so it isn't an eye for White. White has only one eye left, at C1, and its group ends up captured.",
    refutation: 'Not quite. White plays G1: your stone at F1 is in atari (only one liberty, E1). White will take it, and its point will give White a second eye.',
  },
  o10: {
    title: 'From one end',
    prompt: 'Capture the marked stones in three moves or less.',
    explanation: "Superb! Each group has three liberties: this is a capturing race. Fill White's from one end, D1 or F1. If you play D1 and White plays C1, your stone at D1 is in atari, but you play F1: White's stones are too. If White takes D1 by playing E1, its four stones have only one liberty left, D1, and you take them all. In the middle, at E1, your stone would be too weak.",
    refutation: 'Not quite. White plays C1, or F1 if you played E1 or C1, and wins the capturing race. In the middle, at E1, your stone is too weak: F1 puts it in atari and gives White one more liberty, G1. Start from one end, D1 or F1.',
  },
  d08: {
    title: 'The race in the corner',
    prompt: 'Capturing race: your group G6-G9 against the marked white group. Count, then play the winning move.',
    explanation: "Correct! In a capturing race (semeai), you count: White has 4 liberties (J9, J8, J7, J6), so do you (F9, F8, F7, F6), and none is shared by both groups. When it's equal, whoever plays first wins: any of the four points works. Then answer each White move on your liberties with a move on its own.",
    refutation: "Not quite. Each group has 4 liberties. If you don't reduce White's right away, White takes yours (F9, F8, F7, F6) and wins by one move.",
  },
  f09: {
    title: 'Block the way out',
    prompt: 'Capturing race: your group C1-C4 against the marked white group. Careful, White can reach its wall.',
    explanation: "Well done! The white group has 4 liberties: A3, A2, A1 and B5. But B5 isn't like the others: by playing there, White would connect to the white wall at C5. In a capturing race (semeai), where two groups surround each other and whoever takes all the other's liberties first wins, you block the way out first. After B5, White has 3 liberties and you have 4 (D4, D3, D2, D1): you win the race.",
    refutation: 'Not quite. White plays B5 and connects its group to the white wall at C5: it leaves the race and can no longer be captured. Block the way out first.',
  },
  k07: {
    title: 'The helper stone',
    prompt: 'Black to play and capture. Two white stones lie in wait for your ladders, but a black stone helps you.',
    explanation: "Superb! With D5, White runs toward the upper right. Without your stone at G7, the ladder (a series of ataris in a zigzag) would run into the white stone at G8 and White would escape. But G7 is in the way: it blocks the path and takes the place of an atari. It is called a helper stone. Toward the lower left, though, B3 breaks the ladder.",
    refutation: 'Not quite. After E6, White extends to D5 and the ladder heads to the lower left, straight at the white stone at B3: it is broken. Toward the upper right, your stone at G7 protects you from G8.',
  },
  m07: {
    title: 'The bulky five',
    prompt: 'Black to play and kill. The white group has five empty points in the corner: a square of four plus one point.',
    explanation: "Superb! This shape is called the bulky five. Its vital point, B1, touches three of the four other points. If White played there, it would make two eyes; by taking it, you leave White a single space. White can no longer make two eyes (two empty points surrounded by its stones): its group ends up captured.",
    refutation: 'Not quite. White plays B1, the central point: C1 becomes an eye, and White makes a second one in the corner. Its group is alive.',
  },
  o11: {
    title: 'Pick the right side',
    prompt: 'Capture the marked stone in five moves or less.',
    explanation: 'Superb! D3 puts the stone in atari and pushes it toward the left edge. Each time it extends, you put it back in atari: C5, then B5, then A5. It zigzags to the edge, and you take it at A2. This is a ladder. At C4, you were pushing it toward the white stone at E2: White connects to it, and the ladder is broken.',
    refutation: 'Not quite. At C4, White extends to D3, toward its stone at E2: the ladder is broken, White connects to it and escapes. Anywhere else, it also extends to D3. Push it toward the left edge instead, where nothing is waiting.',
  },
  j09: {
    title: 'The point that spoils two eyes',
    prompt: 'Black to play and kill. White has a hole at B2 and the whole first line.',
    explanation: "Superb! B1 touches B2 and A1 at the same time: neither one is an eye anymore (an empty point surrounded by White). On the right, E1 and E2 touch your wall: White can't make two eyes there. A point that spoils two eyes at once is a vital point.",
    refutation: 'Not quite. White plays B1 and has two eyes: B2 and the corner, A1.',
  },
  o12: {
    title: 'The net in the right place',
    prompt: 'Capture the marked stone in three moves or less.',
    explanation: "Well done! E3 doesn't touch the stone, but it closes both its exits, E4 and F3: this is a net. If White comes out at E4, you play D4: it is in atari, and if it extends to F3, you take it at F2. If it comes out at F3, you play F2, then D4.",
    refutation: "Not quite. White extends to F3, or to E4 if you played F3 or F2, and keeps enough liberties to escape. Don't touch the stone: close both its exits.",
  },
  d09: {
    title: 'One liberty on each side',
    prompt: 'Capturing race: each group has one liberty of its own and shares G1 with the other. Play the right move.',
    explanation: "Well done! White has two liberties: J1, its outside liberty (it belongs to White alone), and G1, the liberty shared by both groups. At J1, you put it in atari (only one liberty). If it fills your outside liberty E1, you capture it at G1. In a capturing race (semeai), the shared liberty is filled last.",
    refutation: "Not quite. If you play G1, you also fill your own liberty: your group has only E1 left, and White captures it. Play on White's outside liberty first.",
  },
  f10: {
    title: 'One way out, one shared liberty',
    prompt: 'Capturing race: your group against the marked white group. Each has 3 liberties. Where do you start?',
    explanation: "Well done! In a capturing race (semeai), whoever takes all the other's liberties first wins. White has 3 liberties: J1, its outside liberty (it belongs to White alone), G1, the liberty shared by both groups, and H5, a way out toward the white wall at G5. You have 3 too: E2, E1 and G1. Block the way out at H5 first: White has only 2 liberties against your 3. Then J1, and the shared liberty G1 last: you capture White one move ahead.",
    refutation: 'Not quite. White plays H5 and connects its group to the white wall at G5: it leaves the capturing race. Block the way out first.',
  },
  j10: {
    title: "White's false hopes",
    prompt: 'Black to play and kill. White has three spaces: D3, the corner and D1-E1.',
    explanation: "Well done! D3 isn't an eye: your stone at D4 touches it. White can take A1 at B1 to make an eye in the corner. So it needs another one: E1 takes it away, because D1 now touches your stone. Only one eye: its group ends up captured.",
    refutation: 'Not quite. White plays E1: D1 becomes an eye, and White can take A1 at B1 to make a second one in the corner.',
  },
  k08: {
    title: 'Cut and double threat',
    prompt: 'Black to play and capture white stones. One move threatens two groups at once.',
    explanation: 'Correct! E4 cuts the white stones into two groups. Each has only two liberties left (the empty points next to it): D6 and E5 for one, F3 and G4 for the other. This is a double threat: White can save only one group, and you capture the other.',
    refutation: 'Not quite. White plays E4 and connects all its stones into one group, with enough liberties to escape. The cutting point is also its connecting point.',
  },
  j11: {
    title: 'L-shaped three in the corner',
    prompt: 'Black to play and kill. The empty points A2, A1 and B1 form an L.',
    explanation: "Well done! The vital point of an L of three points is the corner of the L, here A1. C3 and E3 aren't eyes: they touch your wall. After A1, White can make only one eye in the corner, even if it takes your stone. If White played A1 first, it would have two eyes, A2 and B1.",
    refutation: 'Not quite. White plays A1 and has two eyes, A2 and B1.',
  },
  d10: {
    title: 'Outside first',
    prompt: 'Capturing race between your group and the marked white group. C1 touches both groups. Where do you start?',
    explanation: "Well done! In a capturing race (semeai), you fill the outside liberties first: those that belong to the enemy group alone, here A2 and A1. C1 is a shared liberty, belonging to both groups: you fill it last. After A2, White has 2 liberties (A1, C1) and you have 3 (C1, E2, E1): you capture White one move ahead. A1 works too: if White takes your stone at A2, it still has only two liberties.",
    refutation: "Not quite. C1 is a liberty shared by both groups: filling it also takes one of yours. After C1, each side has 2 liberties left and it's White's turn: White plays E2, then E1, and captures your group first.",
  },
  f11: {
    title: 'Way out and shared liberty',
    prompt: 'Capturing race: your group against the marked white group. Count carefully: way out, outside liberties, shared liberty.',
    explanation: "Superb! In a capturing race (semeai), whoever takes all the other's liberties first wins. White has 4 liberties: A2 and A1, its outside liberties (they belong to White alone), C1, the liberty shared by both groups, and B5, a way out toward the white wall at C5. You have 4 too: D3, E2, E1 and C1. Block the way out at B5 first. Then fill A2 and A1 and keep C1 for last: you capture White one move ahead.",
    refutation: 'Not quite. White plays B5 and connects its group to the white wall at C5: it leaves the capturing race. Block the way out first.',
  },
  k09: {
    title: 'The tight net',
    prompt: "Black to play and capture the marked stone. The ladder doesn't work: shut it in.",
    explanation: "Well done! D6 doesn't touch the stone, but it closes both its exits: this is a net (geta in Japanese). If White comes out at E6, you play E7; if it comes out at D5, you play C5. Each time, it is in atari (only one liberty) and you capture it. A looser net, at C6 or D7, leaves too much room: with help from C7 and C8, White escapes.",
    refutation: 'Not quite. A direct atari starts a ladder that the white stones at C7 and C8 break, and a looser net lets White slip toward them. Close in as tight as you can.',
  },
  m08: {
    title: 'The false eye',
    prompt: 'Black to play and kill. White seems to have two eyes, A9 and D9. Look at the diagonal points.',
    explanation: "Well spotted! C8 cuts the white stones into two groups. D9 is now only a false eye: an empty point surrounded by white stones that aren't connected to each other. The stones on the right have only D9 left as a liberty. If White connects at D9, its whole group has only one liberty left, A9, and you capture it. One real eye isn't enough to live.",
    refutation: 'Not quite. White plays C8: all its stones are connected, with two real eyes, A9 and D9. Its group is alive.',
  },
  k10: {
    title: 'Strengthen the cutting stone',
    prompt: 'Your stone at E2 cuts two white groups apart. Black to play and capture one of them.',
    explanation: 'Superb! E3 strengthens your cutting stone, then threatens two things at once: playing D3 to shut in the left group, or F3 to shut in the right one. This is a double threat. If White gets out on one side, you close the other: that group, pressed against the edge, has only two liberties left (the empty points next to it) and you capture it.',
    refutation: 'Not quite. Your stone at E2 has only two liberties, E1 and E3. If you play elsewhere, White plays E3 and puts it in atari: you must defend it, and White has time to save both its groups.',
  },
  m09: {
    title: 'False eye on the edge',
    prompt: 'Black to play and kill. White has two eyes, C9 and F9: one of them can become false.',
    explanation: "Superb! D8 splits the white stones on the left from those on the right. C9 becomes a false eye: an empty point surrounded by stones that aren't connected to each other. The three stones on the left have only C9 left as a liberty. If White connects at C9, its whole group has only one liberty left, F9, and you capture it. One real eye isn't enough to live.",
    refutation: 'Not quite. White plays D8: all its stones are connected, with two real eyes, C9 and F9. Its group is alive.',
  },
  d11: {
    title: 'Four against four',
    prompt: 'Capturing race between your group and the marked white group. Count carefully, then play the winning move.',
    explanation: "Perfect! Each group has 4 liberties: 3 outside liberties (those that belong to it alone) and C1, the shared liberty. In a capturing race (semeai), you fill White's outside liberties first: A3, A2 or A1. Each time White plays on your liberties, you answer on its own. In the end, both groups have only C1 left, it's your turn, and you capture White at C1.",
    refutation: "Not quite. C1 is the shared liberty: filling it also takes one of yours. Each side then has 3 liberties left and it's White's turn: White wins the race by one move.",
  },
  m10: {
    title: 'The pyramid',
    prompt: 'Black to play and live. Four empty points shaped like a pyramid: one point touches all the others.',
    explanation: "Perfect! This four-point shape is called the pyramid four. Its vital point, E1, touches the three others: it is the key point for both players. By taking it, you make three eyes, D1, F1 and E2. An eye is an empty point surrounded by your stones, where White can't play. Two are enough: your group is alive.",
    refutation: 'Not quite. White plays E1, the point that touches the three others: you have only one eye left and your group ends up captured.',
  },
  i01: {
    title: 'Bulky five on the edge',
    prompt: 'Black to play and kill. The white group has five empty points on the edge: a square of four plus one point.',
    explanation: 'Well done! This shape is called the bulky five. Its vital point, E2, touches three of the four other empty points. By taking it, you stop White from making two eyes (two empty points surrounded by its stones). Whatever it does, its group ends up captured.',
    refutation: 'Not quite. White plays E2, the point that touches three of the four others: it makes two eyes, and its group is alive.',
  },
  i02: {
    title: 'Two eyes in the corner',
    prompt: 'Black to play and live. Your group is on the second line, in the corner. One move makes two eyes.',
    explanation: "Well done! B1 makes two eyes at once: A1 and C1. An eye is an empty point surrounded by your stones, where White can't play: it would be suicide. Your stone at D1 closes the second eye. With two eyes, your group is alive forever.",
    refutation: "Not quite. White plays B1: in the corner, you can no longer make two eyes (two empty points surrounded by your stones). Your group can't live anymore.",
  },
  m11: {
    title: 'Kill the pyramid',
    prompt: 'Black to play and kill. The white group has four empty points shaped like a pyramid.',
    explanation: "Well done! E1 is the vital point of the pyramid: it touches the three other empty points. White can no longer make two eyes (two empty points surrounded by its stones). Whatever it does, its group ends up captured. Same shape as for living: the vital point is the same for both players.",
    refutation: 'Not quite. White plays E1, the point that touches the three others: it makes at least two eyes, and its group is alive.',
  },
  i03: {
    title: 'The intruder in the corner',
    prompt: 'Black to play and live. A white stone has come into your corner, at C1.',
    explanation: "Well done! B1 makes an eye at A1 and puts the stone at C1 in atari: it has only one liberty left, D1. If White extends to D1, its two stones have only one liberty left, E1: you capture them, and their place gives you the second eye. An eye is an empty point surrounded by your stones, where White can't play.",
    refutation: "Not quite. White plays B1 and connects its stone at C1: you can no longer make two eyes (two empty points surrounded by your stones). Your group can't live anymore.",
  },
  i04: {
    title: 'Close the edge',
    prompt: 'Black to play and live. A white stone has come into your space, at D1.',
    explanation: 'Superb! E1 puts the stone at D1 in atari: it has only one liberty left, C1. If White extends to C1, B1 captures both stones. Otherwise, you capture D1 at C1. Either way, you keep enough room for two eyes (two empty points surrounded by your stones).',
    refutation: "Not quite. White plays E1 and gives its stone at D1 one more liberty: your corner becomes too small for two eyes. Your group can't live anymore.",
  },
  m12: {
    title: 'Crossed five',
    prompt: 'Black to play and live. Five empty points shaped like a cross: where is the vital point?',
    explanation: "Superb! The vital point of a five-point cross is its center, E2: it touches the four others. By taking it, you make four eyes, D2, F2, E3 and E1. An eye is an empty point surrounded by your stones, where White can't play. Two are enough: your group is alive.",
    refutation: 'Not quite. White plays E2, in the center of the cross: you have only one eye left and your group ends up captured.',
  },
  i05: {
    title: 'The right order',
    prompt: 'Black to play and live. You can make one eye left of D1 and another on the right. Where do you start?',
    explanation: "Superb! B1 makes an eye at C1 right away: an empty point surrounded by your stones, where White can't play. On the right, you have two ways to make the second eye: if White plays F1, you answer G1; if it plays G1, you answer F1. White can't take both. Remember: start where you have only one way to make an eye.",
    refutation: "Not quite. White plays B1: left of D1, you can no longer make an eye, and one eye on the right isn't enough. Your group can't live anymore.",
  },
  d12: {
    title: 'The eye that wins',
    prompt: 'Capturing race: your group has an eye at E1, the marked white group has none. Win the race.',
    explanation: "Excellent! Your group has an eye at E1: an empty point surrounded by your stones, where White can play only last. In this capturing race (semeai), you have 2 liberties, C1 and the eye E1; White has 3, A2, A1 and C1, the liberty shared by both groups. After A2, White can neither play in your eye (it would be suicide) nor play C1 without putting itself in atari. You then play A1, then C1, and capture it. The eye let you win a race where you had fewer liberties.",
    refutation: 'Not quite. If you fill C1, your group has only its eye E1 left: White plays there and captures it. And A1 comes too early: White takes your stone at A2, and you can no longer play A1 again.',
  },
  f12: {
    title: 'The eye and the way out',
    prompt: 'Capturing race: your group has an eye at E9, the marked white group has one more liberty. Win the race.',
    explanation: "Magnificent! Your group has an eye at E9: an empty point surrounded by your stones, where White can play only last. In this capturing race (semeai), White has 4 liberties: A9, A8, C9 (shared by both groups) and B5, a way out toward the white wall at C5. You have 3: the eye E9, C9 and G8. Block the way out at B5 first. Then White can't play in your eye (it would be suicide), and if it fills C9, it also takes one of its own liberties. You fill A8 and A9, then capture it.",
    refutation: 'Not quite. White plays B5 and connects its group to the white wall at C5: it leaves the capturing race. Block the way out first.',
  },
  i06: {
    title: 'Shrink the corner',
    prompt: 'Black to play and kill. The white group is on the second line, in the corner, with a stone at C1.',
    explanation: "Well done! E1 prevents the eye at D1: that point touches your stone, so it isn't surrounded by White anymore. To capture E1, White would have to fill D1 itself. Only the corner is left, A1 and B1: just one eye, and it needs two (two empty points surrounded by its stones). At D1, your stone would have had only one liberty: White would have captured it at E1.",
    refutation: 'Not quite. White plays E1: D1 becomes an eye, and White makes a second one in the corner. Its group is alive.',
  },
  m13: {
    title: 'Kill the cross',
    prompt: 'Black to play and kill. The white group has five empty points shaped like a cross.',
    explanation: 'Well done! E2, the center of the cross, touches the four other empty points: it is the vital point. White can no longer make two eyes (two empty points surrounded by its stones). Whatever it does, its group ends up captured.',
    refutation: 'Not quite. White plays E2, in the center of the cross: it makes several eyes, and its group is alive.',
  },
  i07: {
    title: 'Shrink from the edge',
    prompt: "Black to play and kill. The white stone at D1 splits White's space in two.",
    explanation: "Well done! B1 prevents the eye on the left: C1 touches your stone, so it isn't a point surrounded by White anymore. On the right, E1, F1, G1 and H1 are left: if White plays F1, you play H1; if it plays H1, you play F1. White can no longer make two eyes (two empty points surrounded by its stones): its group ends up captured.",
    refutation: 'Not quite. White plays B1: it makes an eye at C1, and a second one right of D1. Its group is alive.',
  },
  d13: {
    title: 'An eye against four liberties',
    prompt: 'Capturing race: your group has an eye at E9, the marked white group has one more liberty. Win anyway.',
    explanation: "Magnificent! You have 3 liberties: the eye E9, C8 and G9, the liberty shared by both groups. White has 4: J9, J8, J7 and G9. But White can't play in your eye (it would be suicide), and if it plays G9, it also takes one of its own liberties. After J8, you play J7 then J9, and capture White at G9.",
    refutation: "Not quite. White has one more liberty than you: every move counts. Reduce White's outside liberties (those that belong to it alone) and keep G9, the shared liberty, for last.",
  },
  i08: {
    title: 'The rabbit',
    prompt: 'Black to play and kill. The white group has six empty points. Are six points enough to live?',
    explanation: "Superb! This six-point shape is called the rabbity six: a five-point cross plus one diagonal point. Its vital point, E2, touches four of the five other points. By taking it, you stop White from making two eyes (two empty points surrounded by its stones). Whatever it does, its group ends up captured. Six points aren't always enough: shape matters more than size.",
    refutation: 'Not quite. White plays E2, in the center of its space: it makes at least two eyes, and its group is alive.',
  },
};
