-- Issue #136, lot S : tesuji de capture, difficulté 900 à 1250, 9 × 9, Noir au trait.
-- Fermer le côté ouvert contre le bord, filet, couper avant l'atari, échelle cassée, pierre relais, filet à distance.
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-s.test.ts (lecteur exact src/go/lecteurs-lot-n.ts).
-- Aucun ko. Insertion seule : aucun problème existant n'est modifié ni supprimé.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('s01', null, 9, '{"rows":[".........",".........",".........",".........",".........","..XXXX...",".XOTTX...",".X.......","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E2, du côté ouvert, et garde trop de libertés pour être pris en trois coups. Ta pierre B2 ferme déjà la gauche : ferme la droite."}', array['E2'], 'Contre le bord', 'Capture les pierres marquées en trois coups au plus.', 'Bravo ! Les trois pierres blanches ont trois libertés : C2, D2 et E2. À gauche, ta pierre B2 ferme déjà la route. E2 ferme la droite. S''il s''allonge en D2, tu joues D1 ; s''il joue C2, tu joues C1. Il bute sur le bord et sur tes pierres : il reste en atari (une seule liberté), et tu le prends.', 900),
 ('s02', null, 9, '{"rows":[".........",".........",".........","...X...X.","...XT.X..","....X....",".........",".....O...","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en F5, ou en E6 si tu as joué F5 ou F4, et garde assez de libertés pour s''échapper. Ne touche pas la pierre : ferme ses deux sorties."}', array['F6'], 'Le filet entre tes pierres', 'Capture la pierre marquée en trois coups au plus.', 'Bravo ! F6 ne touche pas la pierre, mais ferme ses deux sorties, E6 et F5 : c''est un filet (geta en japonais). Si Blanc sort en E6, tu joues E7 : il est en atari, et s''il s''allonge en F5, tu le prends en F4. S''il sort en F5, tu joues F4, puis E7.', 950),
 ('s03', null, 9, '{"rows":[".........",".........",".........","...O.....",".........","...OXX...","....T....","....X....","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D3 : il relie E3 à sa pierre D4 et s''échappe. Joue d''abord en D3 : tu coupes et tu mets en atari d''un seul coup."}', array['D3'], 'Coupe d’abord', 'Capture la pierre marquée en cinq coups au plus.', 'Superbe ! D3 coupe E3 de sa pierre D4 et le met en atari d''un seul coup. Il s''allonge en F3 : tu joues G3. Il descend en F2 : tu joues G2. Il s''allonge en F1 : il a deux libertés, E1 et G1, contre le bord. Tu joues E1, il s''allonge en G1, et tu le prends en H1. Remettre en atari une pierre qui fuit, c''est une échelle.', 1000),
 ('s04', null, 9, '{"rows":[".........",".........",".........",".........",".........","...XX....","....T....","....X.O..","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en F3, du côté de sa pierre G2, et s''échappe : l''échelle ne marche pas de ce côté. Pousse-le plutôt vers la gauche, où rien ne l''attend."}', array['F3'], 'La pierre qui casse l’échelle', 'Capture la pierre marquée en cinq coups au plus.', 'Superbe ! F3 met la pierre en atari et la pousse vers la gauche, loin de la pierre blanche G2. Il s''allonge en D3 : tu joues C3. Il descend en D2 : tu joues C2. Il s''allonge en D1 : tu joues E1, puis il s''allonge en C1 et tu le prends en B1. C''est une échelle. Si tu joues D3, Blanc s''allonge en F3, vers G2 : il a trois libertés et s''échappe.', 1050),
 ('s05', null, 9, '{"rows":[".........",".........",".........",".........",".........","....XX...","....T....",".....X...","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en D3, vers le centre, et s''échappe. Ferme d''abord cette sortie, sans mettre en atari : ta pierre F2 garde l''autre côté."}', array['D3'], 'Ta pierre relais', 'Capture la pierre marquée en cinq coups au plus.', 'Superbe ! D3 ferme la sortie vers le centre, sans mettre en atari. Si Blanc s''allonge en F3, tu joues G3 : ta pierre F2 le bloque, il est en atari. S''il descend en E2, tu joues D2. Chaque fois, il bute sur le bord et sur ta pierre F2, qui sert de relais : il ne sort plus, et tu le prends.', 1150),
 ('s06', null, 9, '{"rows":[".........",".........","....X....",".......X.","...XT....","....X....",".........","....O....","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en F5, ou en E6 si tu as joué F5 ou F4, et trouve une sortie. Ferme la route de droite de loin, sans coller à la pierre."}', array['G5'], 'Le filet à distance', 'Capture la pierre marquée en cinq coups au plus.', 'Superbe ! G5 ne touche pas la pierre : il ferme la route de droite de loin. C''est un filet à distance. Si Blanc sort en E6, tu joues D6 ; s''il continue en F6, tu joues F7, puis G7 s''il s''allonge en G6. S''il sort en F5, tu joues F4. Tes pierres E7 et H6 ferment le haut : il reste enfermé, et tu le prends.', 1250)
on conflict (id) do nothing;
