-- Issue #136, lot T : problèmes difficiles, difficulté 1100 à 1500, 9 × 9, Noir au trait.
-- Filet contre le bord (capture), vie par un coup au bord, placements sur le premier rang, point de coupe (vie et mort).
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-t.test.ts (lecteur exact src/go/lecteurs-lot-n.ts
-- pour la capture, src/go/preuve-vie-mort.ts pour la vie et la mort). Aucun ko, aucun seki.
-- Insertion seule : aucun problème existant n'est touché.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('t01', null, 9, '{"rows":[".........",".........",".........",".........","XX.......","T........","T........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue B2 : cette pierre lui ouvre la route du bas, et il garde trop de libertés pour être pris en quatre coups. Prends ce point le premier, sans toucher ses pierres."}', array['B2'], 'Le filet contre le bord', 'Capture les pierres marquées en quatre coups au plus.', 'Bravo ! Les deux pierres ont trois libertés : B4, B3 et A2. B2 ne les touche pas : il ferme la sortie du bas, de loin. C''est un filet. Si Blanc s''allonge en B4, tu joues C4 ; s''il s''allonge en B3, tu joues C3. Il reste collé au bord, à court de libertés, et tu le prends au quatrième coup.', 1100),
 ('t02', null, 9, '{"rows":[".........",".........",".........",".........",".........","OOOOO....",".X.XOOO..",".XXXXOO..",".S.O..O.."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E1 : il relie sa pierre D1 et entre dans ton espace par la droite. Il ne te reste pas la place pour deux yeux, et ton groupe finit capturé."}', array['E1'], 'Ferme par le bord', 'Noir joue et vit. Une pierre blanche est entrée en D1, dans ton espace.', 'Bravo ! E1, sur le premier rang, ferme ton espace à droite et met D1 en atari : il ne lui reste qu''une liberté, C1. Si Blanc joue F1, tu prends D1 en C1. La pierre D1 ne peut plus sortir, et ton coin garde la place pour deux yeux : ton groupe est vivant.', 1150),
 ('t03', null, 9, '{"rows":[".........",".........",".........",".........",".........","OOOOO....","XX..OOO..","SX.XXOO..","..O.XXO.."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue B1 et se glisse sous tes pierres : A1 n''est plus un œil. Il ne te reste pas la place pour deux yeux, et ton groupe finit capturé."}', array['B1'], 'L’œil du coin', 'Noir joue et vit. La pierre blanche C1 veut entrer dans ton coin.', 'Superbe ! B1 garde A1, ton premier œil, et bloque la pierre C1 contre le bord. Si Blanc s''allonge en C2, tu joues C3 : ses deux pierres sont en atari. S''il joue C3, tu joues C2. Chaque fois, ses pierres restent enfermées, et ton groupe est vivant.', 1200),
 ('t04', null, 9, '{"rows":[".........",".........",".........",".........",".........","XXXXX....","...OXXX..","OOOO.OX..","T.OO.OX.."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E2 : il relie F1 et F2 au reste du groupe, et E1 devient un deuxième œil, à côté de B1. Avec deux yeux, son groupe est vivant."}', array['E2'], 'Le point de coupe', 'Noir joue et tue. Regarde les pierres blanches F1 et F2.', 'Bravo ! E2 coupe F1 et F2 du reste du groupe et les met en atari. Si Blanc les relie en E1, E1 ne sera jamais un œil. A3, B3 et C3 touchent tes pierres : ce n''est pas un œil non plus. Blanc n''a qu''un œil, en B1, et son groupe finit capturé.', 1250),
 ('t05', null, 9, '{"rows":[".........",".........",".........",".........",".........","XXXXX....",".X.XXXX..",".OOO.OX..",".T.OO.X.."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue A2 : A1 devient un œil, et il garde la place pour un deuxième. Son groupe est vivant."}', array['A2'], 'Glisse-toi au bord', 'Noir joue et tue. Ta pierre B3 est déjà contre le groupe blanc.', 'Superbe ! A2 se glisse sous ta pierre B3, sur le bord : A1 ne peut plus devenir un œil. Si Blanc joue A1 pour mettre A2 en atari, tu te relies en A3. Le coin blanc n''a plus la place pour deux yeux, et son groupe finit capturé.', 1350),
 ('t06', null, 9, '{"rows":[".........",".........",".........",".........",".........","XXXXX....","OOOOXXX..","OO.O..X..","T....OX.."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue C1 : son espace reste d''un seul tenant, assez grand pour deux yeux. Son groupe est vivant."}', array['C1'], 'Le point vital du premier rang', 'Noir joue et tue. L''espace blanc paraît grand : où est son point faible ?', 'Superbe ! C1, sur le premier rang, est le point vital : il coupe l''espace blanc en morceaux. Si Blanc joue D1, tu joues E2 ; s''il joue E2, tu joues D1. Chaque fois, un seul coup marche : il faut lire la suite. Blanc ne peut plus faire deux yeux, et son groupe finit capturé.', 1500)
on conflict (id) do nothing;
