-- Issue #16, lot V : 16 problèmes qui prolongent les leçons 9 à 12 (filet, prise en retour, course aux libertés,
-- faux œil). Faciles (400 à 680), moyens (740 à 1050), plus durs (1150 à 1380). 9 × 9, Noir au trait.
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-v.test.ts : lecteur exact src/go/lecteurs-lot-n.ts
-- pour capturer et sauver (avec et sans ko), src/go/preuve-vie-mort.ts en zone fermée pour vivre et tuer (recherche
-- complète, un ko compte comme non résolu). Aucun ko, aucun seki.
-- Insertion seule : aucun problème existant n'est touché.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('v01', null, 9, '{"rows":[".........",".........",".........","...XX....","..XTTX...","....X....",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D4 et s''allonge : tu ne peux plus prendre ses pierres en un coup."}', array['D4'], 'La dernière liberté', 'Capture les pierres marquées en un coup.', 'Bravo ! Les deux pierres blanches n''avaient plus qu''une liberté, D4 : elles étaient en atari. Tu joues sur cette dernière liberté et tu les captures toutes les deux.', 400),
 ('v02', null, 9, '{"rows":[".........",".........",".........","....O....","...OSO...",".........","....X....",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E4 : ta pierre E5 n''a plus de liberté, elle est capturée."}', array['E4'], 'Rejoins tes amies', 'Ta pierre marquée est en atari (une seule liberté). Sauve-la.', 'Bravo ! E4 relie ta pierre à E3. Ensemble, elles ont maintenant plusieurs libertés : Blanc ne peut plus les prendre. Pour sauver une pierre en atari, allonge-la vers tes pierres.', 450),
 ('v03', null, 9, '{"rows":[".........",".........","..X......",".XT.X....","...X.....",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue C5 : sa pierre s''allonge vers le bas et garde assez de libertés. Mets-la en atari de l''autre côté."}', array['C5'], 'Pousse-la vers ton mur', 'Capture la pierre marquée en deux coups au plus.', 'Bravo ! C5 met C6 en atari : il ne lui reste que D6. Si Blanc s''allonge en D6, il bute sur tes pierres E6 et D5 : il est encore en atari, et tu le prends en D7. Mets en atari du côté qui pousse vers tes pierres.', 500),
 ('v04', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","...XO....","..XOSO...",".....O..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E1 (ou D1 si tu as joué E1) : ta pierre n''a plus de liberté, elle est capturée."}', array['D1'], 'Prends la pierre qui serre', 'Ta pierre marquée est en atari (une seule liberté). Sauve-la.', 'Bravo ! La pierre blanche D2 était en atari elle aussi : D1 la capture. Ta pierre E2 gagne une liberté en D2, et Blanc ne peut plus la prendre. En E1, elle serait restée en atari.', 560),
 ('v05', null, 9, '{"rows":[".........",".........",".........",".........",".........","...X.....","..XT.....","....X....","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E3 : sa pierre s''allonge vers le haut et s''échappe."}', array['E3'], 'Petite échelle', 'Capture la pierre marquée en quatre coups au plus.', 'Bravo ! E3 met D3 en atari et la pousse vers le bord. Si Blanc s''allonge en D2, C2 le remet en atari ; en D1, E1 recommence. Au bord, il n''a plus de place : tu le prends en B1. C''est une échelle, une suite d''atari en zigzag.', 620),
 ('v06', null, 9, '{"rows":[".........",".........",".........","...X.....","...T.....","...XTX...",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E5 : il relie ses deux pierres, qui ont alors assez de libertés."}', array['E5'], 'Deux atari à la fois', 'Capture une des pierres marquées en deux coups au plus.', 'Bravo ! E5 met les deux pierres en atari à la fois : c''est un double atari. Blanc ne peut en sauver qu''une. S''il s''allonge en C5, tu prends E4 en E3. S''il s''allonge en E3, tu prends D5 en C5.', 680),
 ('v07', null, 9, '{"rows":[".........",".........",".........",".........",".....X...",".....TX..","....X....",".........",".......X."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E4 : sa pierre s''allonge vers la gauche et s''échappe."}', array['E4'], 'L''échelle jusqu''au bout', 'Capture la pierre marquée en cinq coups au plus.', 'Superbe ! E4 met F4 en atari du côté du centre. S''il s''allonge en F3, F2 le remet en atari. Puis G3 appelle H3, et G2 appelle H2. Ta pierre H1 ferme la dernière porte : tu le prends en F1. Avant de lancer une échelle, suis-la jusqu''au bout.', 740),
 ('v08', null, 9, '{"rows":[".........",".........",".........",".........","..X......","..XT.X...","...X.....",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E4 (ou D5 si tu as joué E4 ou E3) : sa pierre s''allonge et s''échappe."}', array['E5'], 'Le filet', 'Capture la pierre marquée en trois coups au plus.', 'Bravo ! E5 est un filet (geta) : tu ne touches pas la pierre, tu fermes ses sorties. Si Blanc sort en D5, D6 le remet en atari ; s''il sort en E4, E3 le remet en atari. Il bute chaque fois sur tes pierres, et tu le prends au coup suivant.', 800),
 ('v09', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........",".O.XXX...",".OX.TX...",".OO.TX..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D1 : il relie E1 et E2 à son groupe de gauche, et elles respirent."}', array['D1'], 'Donne une pierre', 'Capture les pierres marquées en deux coups au plus.', 'Superbe ! D1 donne une pierre : Blanc peut la prendre en D2. Mais alors ses trois pierres n''ont plus qu''une liberté, D1. Tu rejoues en D1 et tu les prends toutes. C''est une prise en retour (snapback).', 850),
 ('v10', null, 9, '{"rows":[".........",".........",".........","..X......",".XTX.....","..TX.....","...T.....","...XX....","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue C3 : il relie toutes ses pierres, qui ont alors assez de libertés."}', array['C3'], 'Le point de coupe', 'Capture une des pierres marquées en deux coups au plus.', 'Bravo ! C3 coupe et met les deux groupes blancs en atari : C5-C4 n''a plus que B4, D3 n''a plus que E3. Blanc ne peut en sauver qu''un : tu prends l''autre au coup suivant.', 900),
 ('v11', null, 9, '{"rows":[".........",".........",".........",".........",".........","...X.....","...XT....","....XX...","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue F3 (ou E4 si tu as joué F3 ou G3) : sa pierre s''allonge et s''échappe."}', array['F4'], 'Ferme les deux portes', 'Capture la pierre marquée en trois coups au plus.', 'Bravo ! F4 est un filet : il ferme les deux sorties sans toucher la pierre. Si Blanc sort en E4, E5 le remet en atari ; s''il sort en F3, G3 le remet en atari. Tu le prends au coup suivant.', 980),
 ('v12', null, 9, '{"rows":[".OO.TX...",".OX.TX...","...XTX...","....X....",".........",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D9 : il relie ses pierres à son groupe de gauche."}', array['D9'], 'Prends-en quatre', 'Capture les pierres marquées en deux coups au plus.', 'Superbe ! D9 donne une pierre. Si Blanc la prend en D8, ses quatre pierres n''ont plus qu''une liberté, D9 : tu reprends là et tu les captures toutes. En D8, tu l''aurais laissé se relier en D9 à ses pierres de gauche.', 1050),
 ('v13', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXXOOOOO","XTTTXXXOO","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue F1 (ou E1 si tu as joué F1, ou D1 si tu as joué C1) : il bouche tes libertés plus vite que toi, et il gagne la course."}', array['B1','D1'], 'Par un bout', 'Course aux libertés : tes pierres E2, F2 et G2 sont enfermées elles aussi. Capture les pierres marquées en trois coups au plus.', 'Superbe ! Compte : Blanc a trois libertés, B1, C1 et D1 ; toi aussi, E1, F1 et G1. Tu joues d''abord : bouche une liberté blanche par un bout, B1 ou D1. Ensuite, chaque fois que Blanc bouche une des tiennes, bouches-en une des siennes. En C1, au milieu, ta pierre serait mise en atari par B1 ou D1.', 1150),
 ('v14', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","OOOOOO...","SX.XXO...",".X.X.O..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue C2 : il coupe ton groupe en deux. C1 devient un faux œil, et ton groupe finit capturé."}', array['C2'], 'Un œil à deux maîtres', 'Noir joue et vit. Regarde C1 : est-ce un vrai œil ?', 'Bravo ! C2 relie tes deux morceaux : A1 et C1 deviennent deux vrais yeux, et ton groupe vit. Si Blanc jouait C2, D1, D2 et E2 ne tiendraient au reste que par C1 : C1 ne serait plus qu''un faux œil, et ton groupe finirait capturé.', 1220),
 ('v15', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXXXXXX.","XOO.OOOX.","XT.O..OX."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D2 : il relie toutes ses pierres, et C1 et E1-F1 lui font deux yeux. Son groupe est vivant."}', array['D2'], 'Le coin de l’œil', 'Noir joue et tue. Regarde l’œil blanc C1 et ses coins.', 'Superbe ! D2 prend le coin de l''œil C1. La pierre D1 ne tient plus au reste que par C1 : C1 est un faux œil. À droite, E1 et F1 ne font qu''un œil. Blanc ne peut plus faire deux vrais yeux, et son groupe finit capturé.', 1300),
 ('v16', null, 9, '{"rows":[".........",".........",".........",".........",".........","XXXXXX...",".T..OX...",".OOO.X...","O.OOOX..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue A3 : A2 et B1 deviennent deux yeux. Son groupe est vivant."}', array['A3'], 'Le point du bord', 'Noir joue et tue. Blanc a de la place dans le coin : où est son point faible ?', 'Superbe ! A3, sur le bord, est le point vital : A2 ne peut plus devenir un œil, et il ne reste que B1. Si tu jouais A2 tout de suite, Blanc prendrait ta pierre en A3, et A2 redeviendrait un œil.', 1380)
on conflict (id) do nothing;
