-- Issue #136, lot P : difficulté 660 à 800, 9 × 9, Noir au trait.
-- Atari contre un mur, double atari, prise en retour sur le bord.
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-p.test.ts. Aucun seki, aucun ko.
-- Insertion seule : aucun problème existant n'est modifié ni supprimé.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('p01', null, 9, '{"rows":[".........",".........",".........",".........","..XX.X...","..XTT.X..","...XX....",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en E5, ou en F4 si tu as joué E6, et garde deux libertés. Mets-le en atari tout de suite, du côté de tes pierres."}', array['E5','F4'], 'Contre ton mur', 'Capture les pierres marquées en deux coups au plus.', 'Bravo ! Les pierres marquées ont deux libertés, E5 et F4. Joue sur l''une d''elles : les pierres sont en atari (une seule liberté). Si Blanc s''allonge sur l''autre, il bute sur tes pierres F5 et G4 : il est encore en atari, et tu le prends.', 660),
 ('p02', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","...X.X...","..XT.TX..","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E2 : il relie ses deux pierres, et le groupe a quatre libertés. Joue le point qui touche les deux pierres à la fois."}', array['E2'], 'Deux atari d’un coup', 'Capture une pierre marquée en deux coups au plus.', 'Bravo ! E2 se place entre les deux pierres et les met toutes les deux en atari : c''est un double atari. Blanc ne peut en sauver qu''une. S''il s''allonge en D1, tu prends F2 en F1. S''il s''allonge en F1, tu prends D2 en D1.', 720),
 ('p03', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","..XXXX...",".XOO.X...",".XTT.OOO."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E1 : il relie ses quatre pierres à F1, G1 et H1, et le groupe respire. Joue plutôt en E1, même si Blanc peut prendre ta pierre."}', array['E1'], 'Donne une pierre, prends-en cinq', 'Capture les pierres marquées en deux coups au plus.', 'Superbe ! En E1, ta pierre n''a qu''une liberté, E2. Mais les quatre pierres blanches n''ont plus qu''une liberté elles aussi, E2 : elles sont en atari. Si Blanc prend en E2, ses cinq pierres n''ont qu''une liberté, E1. Tu rejoues en E1 et tu les captures toutes. C''est une prise en retour : tu donnes une pierre pour en prendre cinq.', 800)
on conflict (id) do nothing;
