-- Issue #500, lot Y : problèmes de fin de partie (yose) pour la série « Fin de partie » des problèmes par thème (#471),
-- qui attendait d'en avoir 8. 9 × 9, Noir au trait, difficulté 650 à 800 (ouverts à un débutant).
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-y.test.ts : minimax exact de src/go/preuve-fin-de-partie.ts
-- (alpha-bêta, bornes basse et haute égales) sur les endroits encore ouverts, en comptage par surfaces ; la réponse est le
-- seul meilleur coup, avec l'écart annoncé ; les chiffres des textes sont recomptés en règle japonaise.
-- Même contenu que src/content/lots/y-fin-de-partie.ts. Insertion seule : aucun problème existant n'est touché.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('y01', null, 9, '{"rows":["...XO....","...XO....","...XO....","...XO....","...XO....","...XO....","...XO....","XXXXOOOOO","....O...."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D1 : il avance sur le premier rang, ta frontière recule en C1, et tu perds au moins un point."}', array['D1'], 'Bloque au premier rang', 'Blanc est descendu en E1, sur le premier rang. Ferme ta frontière sans perdre de point.', 'Bravo ! D1 bloque au contact de la pierre blanche : A1, B1 et C1 restent à toi. En C1, tu reculais : Blanc avançait en D1, et tu avais un point de moins.', 650),
 ('y02', null, 9, '{"rows":[".XOO.O...",".XXX.O...","..XOOO...","..XO.....","..XO.....","..XO.....","..XO.....","XXXOOOOOO","...O....."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E9 : il relie ses deux pierres, et tu ne gagnes rien en haut. Les prendre valait 4 points, bloquer en bas un seul."}', array['E9'], 'Le plus gros d’abord', 'Il reste deux endroits ouverts, en haut et en bas. Joue le plus gros.', 'Bravo ! E9 prend C9 et D9 : 2 prisonniers, et ces deux points deviennent ton territoire. Ça fait 4 points. En bas, si Blanc avance en C1 et que tu bloques en B1, tu ne perds qu’un point.', 700),
 ('y03', null, 9, '{"rows":["...XO....","...XO....","...XO....","...XO....","....XO...","....XO...","....XO...","XXXXXOOOO",".......O."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue F1 : c’est lui qui avance sur le premier rang, et tu perds au moins un point."}', array['F1'], 'Pas besoin de relier', 'Tes pierres D6 et E5 se touchent en diagonale. Faut-il relier en D5 ? Joue le coup qui rapporte le plus.', 'Bravo ! F1 contourne la pierre blanche F2 par le premier rang : c’est un hane. Blanc bloque en G1, tu relies en E1, et son territoire perd un point. D5 est déjà dans ton territoire : y jouer te coûterait un point, et Blanc jouerait F1 avant toi.', 750)
on conflict (id) do nothing;
