-- Issue #16, lot W : 9 problèmes d'entraînement pour les leçons 14 à 16, trois par leçon : seki (w01 à w03),
-- finir la partie (w04 à w06), compter (w07 à w09). 9 × 9, Noir au trait, difficulté 400 à 800 (ouverts à un débutant).
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-w.test.ts : seki par src/go/preuve-vie-mort.ts en zone
-- fermée (la réponse donne un seki pur, tout autre coup laisse Blanc vivre) ; fin de partie et comptage par score()
-- (règle japonaise, komi 6,5 à Blanc, les points d'un seki ne comptent pas) et recherche complète des coups de frontière.
-- Insertion seule : aucun problème existant n'est touché.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('w01', null, 9, '{"rows":[".XO.S.S.O",".XOOOOOOO",".XXXXXXXX",".........",".........",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue F9 : tes pierres restent coupées en deux, et Blanc les capture."}', array['F9'], 'Relie au milieu', 'Sauve tes pierres marquées par un seki (vie commune).', 'Bravo ! F9 relie tes trois pierres. Elles partagent deux libertés avec Blanc, D9 et H9 : qui en remplit une se met en atari et se fait prendre. Personne ne joue là : c''est seki, tout le monde vit.', 500),
 ('w02', null, 9, '{"rows":[".........",".........",".........",".........",".........","XXXXX....","OOOOX....","O.SOX....","S..OX...."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue B1 : il prend A1, et son groupe vit."}', array['B1'], 'Seki dans le coin', 'Sauve tes pierres marquées par un seki (vie commune).', 'Bravo ! B1 sauve A1. Tes pierres et le groupe blanc partagent deux libertés, B2 et C1 : qui en remplit une se met en atari. Personne ne joue là : c''est seki.', 600),
 ('w03', null, 9, '{"rows":[".........",".........",".........",".........",".........","XXXXX....","OOOOX....","..SOX....","S.OOX...."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue B2 : il prend C2, et son groupe vit."}', array['B2'], 'Deux libertés partagées', 'Sauve tes pierres marquées par un seki (vie commune).', 'Bravo ! B2 sauve C2. Tes pierres et le groupe blanc partagent deux libertés, A2 et B1 : qui en remplit une se met en atari. Personne ne joue là : c''est seki.', 700),
 ('w04', null, 9, '{"rows":[".........",".........",".........","OOOOOO...","XXXX.OOOO","...X.XXXX",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E5, au contact de tes pierres : ta frontière se ferme en E4, et tu perds au moins un point."}', array['E5'], 'Ferme au contact', 'Avant de passer : ta frontière est encore ouverte. Ferme-la sans perdre de point.', 'Bravo ! E5 ferme ta frontière au contact de Blanc : E4 reste dans ton territoire. En E4, tu fermais aussi, mais E5 devenait un point neutre (dame) : un point de moins.', 450),
 ('w05', null, 9, '{"rows":["...XO....","...XO....","...X.O...","...XXO...","...XO....","...XO....",".....O...","...XXO...","....XO..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E3, au contact de tes pierres : ta frontière se ferme en D3, et tu perds au moins un point. La dame E7, elle, ne vaut rien."}', array['E3'], 'Dame ou frontière ?', 'Il reste une dame (point neutre) et une frontière ouverte. Joue le coup qui compte.', 'Bravo ! E3 ferme ta frontière au contact de Blanc : D3 reste à toi. La dame E7 ne rapporte rien à personne : on la remplit à la fin.', 550),
 ('w06', null, 9, '{"rows":["TX.......",".X.......","X........",".........","XXXXX.XXX","OOOOX.OOO","....OO...",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue F4, au contact de tes pierres : ta frontière se ferme en F5, et tu perds au moins un point. A9 est déjà morte : inutile de la prendre."}', array['F4'], 'Elle est déjà morte', 'La pierre blanche marquée est morte. Une frontière est encore ouverte : joue le coup qui rapporte le plus.', 'Bravo ! F4 ferme ta frontière au contact de Blanc : F5 reste à toi. A9 ne peut plus vivre : à la fin, on la retire et elle devient prisonnière, sans dépenser de coup.', 650),
 ('w07', null, 9, '{"rows":[".....XO..",".....XO..","....XO...","....XO...","...X.O...","...XO....","...XO....","..XO.....","..XO....."],"toPlay":"B","refutation":"Pas tout à fait. Ce point n''est entouré que par une couleur : c''est du territoire. La dame touche des pierres noires et blanches."}', array['E5'], 'Le point neutre', 'La partie est finie. Avant de compter, remplis le seul point neutre (dame).', 'Bravo ! E5 touche Noir et Blanc : il n''est à personne. On le remplit, et le compte ne change pas : 31 points de territoire chacun, plus le komi pour Blanc.', 400),
 ('w08', null, 9, '{"rows":["...OX..XT","...OX..X.","...OX...X","...O.....","...OX....","...OX....","...OX....","...OX....","...OX...."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E6 : ta frontière se ferme en F6, et tu as 33 points au plus. Blanc a 27 + 6,5 = 33,5 : il gagne."}', array['E6'], 'Le demi-point', 'Komi : 6,5 points pour Blanc. Compte bien : un seul coup te fait gagner.', 'Bravo ! Après E6, tu as 33 points de territoire (J9 comprise, une fois retirée) + 1 prisonnier = 34. Blanc a 27 + 6,5 = 33,5. Tu gagnes d''un demi-point. En F6, tu n''en avais que 33 : Blanc gagnait.', 700),
 ('w09', null, 9, '{"rows":["....XOOO.",".....XXO.",".......O.",".....XO..",".....XO..","XXXXXXO..","OOOOXO...","O.XOXO...","XX.OXO..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue G7 : ta frontière se ferme en F7, et Blanc gagne. Ne remplis jamais B2 ou C1 : dans le seki, tu te mettrais en atari."}', array['G7'], 'Le seki ne compte pas', 'Komi : 6,5 points pour Blanc. Compte, seki compris : un seul coup te fait gagner.', 'Bravo ! G7 ferme au contact : tu as 25 points. B2 et C1, dans le seki, ne sont à personne. Blanc a 18 + 6,5 = 24,5. Tu gagnes d''un demi-point. En F7, tu n''en avais que 24.', 800)
on conflict (id) do nothing;
