-- Issue #136, lot J : captures en deux ou trois coups (double atari par la coupe, prise en retour,
-- capturer pour relier) et vie et mort de 800 à 1000 (points vitaux, quatre en ligne sur le bord, trois en L dans le coin), 9 × 9, Noir au trait.
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-j.test.ts. Aucun seki, aucun ko.
-- Insertion seule : aucun problème existant n'est modifié ni supprimé.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('j01', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXXXXX..","XT.T..X..","...XX.X.."],"toPlay":"B","refutation":"Pas tout à fait. Si tu mets une seule pierre en atari, Blanc relie ses deux pierres en C2 et retrouve deux libertés. Joue plutôt au point qui les sépare."}', array['C2'], 'La coupe qui menace deux fois', 'Capture une des pierres marquées en deux coups au plus.', 'Bravo ! C2 coupe les deux pierres blanches. Chacune n''a plus qu''une liberté : B1 pour B2, E2 pour D2. Elles sont toutes les deux en atari (une seule liberté). C''est un double atari : Blanc n''en sauve qu''une, tu prends l''autre.', 620),
 ('j02', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXXXXX..","T.X...X..","O.OOO.X.."],"toPlay":"B","refutation":"Pas tout à fait. En B2, tu mets les pierres en atari, mais Blanc joue B1 : il les relie à ses pierres du bas et retrouve trois libertés. Joue plutôt en B1, même si Blanc peut prendre ta pierre."}', array['B1'], 'Prise en retour dans le coin', 'Capture la pierre marquée en deux coups au plus.', 'Superbe ! En B1, ta pierre n''a qu''une liberté, B2 : Blanc peut la prendre. Mais A2 et A1 sont en atari (une seule liberté). Si Blanc prend en B2, ses trois pierres n''ont plus qu''une liberté, B1. Tu rejoues en B1 et tu les captures toutes. C''est la prise en retour : tu donnes une pierre pour en prendre trois.', 660),
 ('j03', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXXXXX..",".X.XTOX..","X.OO..X.."],"toPlay":"B","refutation":"Pas tout à fait. En F1, Blanc joue E1 : il relie ses pierres à C1 et D1, et le groupe a deux libertés, B1 et C2. Joue plutôt en E1, même si Blanc peut prendre ta pierre."}', array['E1'], 'Le piège sur le bord', 'Capture la pierre marquée en deux coups au plus.', 'Bravo ! En E1, ta pierre n''a qu''une liberté, F1, et Blanc peut la prendre. Mais E2 et F2 sont en atari (une seule liberté). Si Blanc prend en F1, ses trois pierres n''ont plus qu''une liberté, E1 : tu rejoues en E1 et tu les captures. C''est une prise en retour. Et E1 empêche Blanc de se relier à C1 et D1.', 700),
 ('j04', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXXXXX..","XTO.TOX..",".OX..OX.."],"toPlay":"B","refutation":"Pas tout à fait. Si tu mets un seul groupe en atari, Blanc joue D2 : il relie ses deux groupes, et ils respirent. Coupe d''abord en D2."}', array['D2'], 'Coupe malgré la menace', 'Capture une des pierres marquées en deux coups au plus.', 'Superbe ! D2 coupe et met les deux groupes en atari (une seule liberté) : A1 pour celui de gauche, E1 pour celui de droite. Ta pierre C1 est en atari aussi. Mais si Blanc la prend en D1, le groupe de droite reste en atari : tu le captures en E1.', 760),
 ('j05', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXXXXXX.","XTOOOOOX.","XO..O..X."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue G1 : F1 devient un œil, et C1-D1 en donne un second. Son groupe est vivant."}', array['G1'], 'Ferme depuis l''extérieur', 'Noir joue et tue. Le groupe blanc a deux espaces sur le bord : C1-D1 et F1-G1.', 'Bravo ! G1 s''appuie sur ta pierre H1 et touche F1 : F1 n''est plus un œil (un point vide entouré par Blanc). Il reste à Blanc l''espace C1-D1, qui ne fait qu''un œil. Avec un seul œil, son groupe finit capturé. En F1, ta pierre n''aurait eu qu''une liberté : Blanc l''aurait prise en G1.', 800),
 ('j06', null, 9, '{"rows":[".........",".........",".........",".........",".........","XXXXXX...","XTO.OX...","O.O.OX...","OOOOOX..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D3 et a deux yeux, B2 et D2. Si tu entres en D2, ta pierre n''a qu''une liberté : Blanc la prend en D3."}', array['D3'], 'L''œil touché par le haut', 'Noir joue et tue. Blanc a un œil en B2. Peut-il en faire un second ?', 'Bravo ! D3 s''appuie sur ton mur et touche D2 : D2 n''est plus un œil (un point vide entouré par Blanc). Il ne reste à Blanc qu''un œil, en B2. S''il remplit D2, il n''a toujours qu''un œil, et son groupe finit capturé.', 830),
 ('j07', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","OOOOOOO..","XSXXXXO..",".....OO.."],"toPlay":"B","refutation":"Pas tout à fait. Si tu joues A1 ou C1, Blanc joue E1 : ton espace devient trop petit pour deux yeux. Si tu joues D1, Blanc joue B1, et c''est pareil."}', array['B1','E1'], 'Quatre en ligne sur le bord', 'Noir joue et vit. Tu as cinq points vides sur la première ligne, de A1 à E1.', 'Bravo ! E1 bloque Blanc et te laisse quatre points en ligne, de A1 à D1. Quatre points en ligne sur le bord font deux yeux : si Blanc joue B1, tu réponds C1, et inversement. B1 marche aussi : il fait un œil dans le coin, en A1. Si Blanc joue ensuite D1, tu réponds E1, et inversement.', 860),
 ('j08', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXXXXXX.","XTOOOOOX.","XO.O.X.X."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue G1 : ta pierre F1 est en atari (une seule liberté, E1). Blanc la prendra, et sa place lui donnera un second œil."}', array['G1'], 'Garde ta pierre dedans', 'Noir joue et tue. Ta pierre F1 est entrée dans le camp blanc.', 'Bravo ! Ta pierre F1 n''avait que deux libertés, E1 et G1. G1 la relie à H1 : elle est sauvée. E1 touche F1, ce n''est donc pas un œil pour Blanc. Il ne lui reste qu''un œil, en C1, et son groupe finit capturé.', 880),
 ('j09', null, 9, '{"rows":[".........",".........",".........",".........",".........","XXXXXX...","TOOOOX...","O.OO.X...",".....X..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue B1 et a deux yeux : B2 et le coin, A1."}', array['B1'], 'Le point qui gâche deux yeux', 'Noir joue et tue. Blanc a un trou en B2 et toute la première ligne.', 'Superbe ! B1 touche B2 et A1 en même temps : aucun des deux n''est plus un œil (un point vide entouré par Blanc). À droite, E1 et E2 touchent ton mur : Blanc n''y fait pas deux yeux. Un point qui gâche deux yeux à la fois, c''est un point vital.', 920),
 ('j10', null, 9, '{"rows":[".........",".........",".........",".........",".........","XXXXXX...","TOO.OX...","OOOOOX...","X.O..X..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E1 : D1 devient un œil, et il peut prendre A1 en B1 pour en faire un second dans le coin."}', array['E1'], 'Les faux espoirs de Blanc', 'Noir joue et tue. Blanc a trois espaces : D3, le coin et D1-E1.', 'Bravo ! D3 n''est pas un œil : ta pierre D4 le touche. Blanc peut prendre A1 en B1 pour faire un œil dans le coin. Il lui en faut donc un autre : E1 le lui enlève, car D1 touche maintenant ta pierre. Un seul œil : son groupe finit capturé.', 950),
 ('j11', null, 9, '{"rows":[".........",".........",".........",".........",".........","XXXXXX...","TO.O.X...",".OOOOX...","..OOOX..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue A1 et a deux yeux, A2 et B1."}', array['A1'], 'Trois en L dans le coin', 'Noir joue et tue. Les points vides A2, A1 et B1 forment un L.', 'Bravo ! Le point vital d''un L de trois points est le coin du L, ici A1. C3 et E3 ne sont pas des yeux : ils touchent ton mur. Après A1, Blanc ne peut faire qu''un œil dans le coin, même s''il prend ta pierre. Si Blanc jouait A1 le premier, il aurait deux yeux, A2 et B1.', 980),
 ('j12', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........",".O.....O.","..XXTXX..","........."],"toPlay":"B","refutation":"Pas tout à fait. En E1, Blanc s''allonge en E3 et a trois libertés : sa pierre s''échappe, et tes pierres restent coupées. Mets-la en atari par le haut, pour la pousser vers le bord."}', array['E3'], 'Capture pour relier', 'Capture la pierre marquée en trois coups au plus. Elle coupe tes pierres en deux.', 'Bravo ! E3 met la pierre en atari (il ne lui reste qu''une liberté, E1) et la pousse vers le bord. Si Blanc s''allonge en E1, ses deux pierres ont deux libertés, D1 et F1. Tu en prends une, par exemple D1 : Blanc s''allonge en F1 et n''a plus que G1. Tu captures en G1. Tes deux groupes sont reliés.', 780)
on conflict (id) do nothing;
