-- Issue #16, lot X : 8 problèmes d'entraînement pour les leçons 4 (le ko), 6 (territoire et ouverture) et 8
-- (les premiers coups). Noir au trait, difficulté 350 à 550 (ouverts à un débutant).
-- - Ko (x01 à x03), 9 × 9 : prendre un ko, fermer un ko, prendre un ko pour sauver sa pierre. Prouvés par
--   src/go/lot-x.test.ts avec les règles de src/go (seule réponse, ko vérifié, réfutations vérifiées).
-- - Ouverture (x04 à x08), 13 × 13 : un seul coin libre ; les réponses sont ses points 3-3, 3-4, 4-3 et 4-4. Géométrie
--   vérifiée par src/go/lot-x.test.ts ; chaque position contrôlée par KataGo (réseau g170 b6c96) : le meilleur coup
--   est une réponse, chaque réponse en est à moins de 2,5 points, et chaque coup des deux premières lignes perd au
--   moins 1 point de plus que la moins bonne réponse.
-- La leçon 7 (compter) reprend les problèmes du lot W : aucune ligne ici.
-- Commun à tous (owner_id null). Insertion seule : aucun problème existant n'est touché.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('x01', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........",".........","XXO......","XT.O....."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue C1 : il relie la pierre marquée à ses pierres, et elle est sauvée."}', array['C1'], 'Prends le ko', 'La pierre blanche marquée n’a plus qu’une liberté. Capture-la.', 'Bravo ! C1 prend B1. Ta pierre C1 n’a plus qu’une liberté, B1 : c’est un ko. Blanc ne peut pas reprendre tout de suite. Il doit d’abord jouer ailleurs.', 350),
 ('x02', null, 9, '{"rows":["..OS.X...","..OOX....",".........",".........",".........",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E9 : il prend ta pierre, et c’est un ko. Ferme-le avant."}', array['E9'], 'Ferme le ko', 'Ta pierre marquée est en atari. Blanc peut la prendre et lancer un ko. Empêche-le.', 'Bravo ! E9 relie ta pierre à tes autres pierres : elles ont trois libertés, et il n’y a plus de ko. On dit que tu as fermé le ko.', 450),
 ('x03', null, 9, '{"rows":[".........","....O....","...O.O...","...OSO...","...XO.O..","....XO...",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue F5 : il relie E5, et ta pierre marquée reste en atari. En E7, tu n’aurais aucune liberté : c’est interdit."}', array['F5'], 'Le ko qui sauve', 'Ta pierre marquée est en atari, et tu ne peux pas t’allonger. Sauve-la.', 'Bravo ! F5 prend E5 : ta pierre retrouve une liberté. C’est un ko : Blanc ne peut pas reprendre en E5 tout de suite. S’il joue ailleurs, relie-toi en E5 : le ko est fini.', 550),
 ('x04', null, 13, '{"rows":[".............",".............",".............",".........O...",".............",".............",".............",".............",".............","...X.....O...",".............",".............","............."],"toPlay":"B","refutation":"Pas tout à fait. Blanc prend alors le coin en haut à gauche, le plus grand point. Joue d’abord dans le coin libre, sur la 3e ou la 4e ligne."}', array['D10','C10','D11','C11'], 'Le coin libre', 'Début de partie. Un coin est encore vide. Prends-le.', 'Bravo ! Le coin en haut à gauche était libre : c’est le plus grand point. Dans un coin, peu de pierres entourent beaucoup de points. Le 3-3, le 3-4 et le 4-4 (3e ou 4e ligne depuis chaque bord) y sont tous bons.', 350),
 ('x05', null, 13, '{"rows":[".............",".............",".............","...O.....X...",".............",".............",".............",".............",".............",".........O...",".............",".............","............."],"toPlay":"B","refutation":"Pas tout à fait. Blanc prend alors le coin en bas à gauche, le plus grand point. Joue d’abord dans le coin libre, sur la 3e ou la 4e ligne."}', array['D4','D3','C4','C3'], 'Coins d’abord', 'Blanc a deux coins, toi un seul. Où joues-tu ?', 'Bravo ! Le coin en bas à gauche était libre : c’est le plus grand point. Le 3-3, le 3-4 et le 4-4 (3e ou 4e ligne depuis chaque bord) y sont tous bons.', 400),
 ('x06', null, 13, '{"rows":[".............",".............",".............","...O.....X...",".............",".............",".............",".............",".............","..X..........","......O......",".............","............."],"toPlay":"B","refutation":"Pas tout à fait. Blanc prend alors le coin en bas à droite, à côté de sa pierre G3 : le plus grand point. Joue d’abord dans le coin libre, sur la 3e ou la 4e ligne."}', array['K4','K3','L4','L3'], 'Avant le bord', 'Blanc vient de jouer sur le bord, en G3. Le plus grand point est ailleurs. Joue-le.', 'Bravo ! Le coin en bas à droite était encore libre : il vaut plus qu’un point du bord. Coins, puis bords, puis centre. Le 3-3, le 3-4 et le 4-4 y sont tous bons.', 450),
 ('x07', null, 13, '{"rows":[".............",".............",".............","...X.....O...",".............",".............","......O......",".............",".............",".........X...",".............",".............","............."],"toPlay":"B","refutation":"Pas tout à fait. Blanc prend alors le coin en bas à gauche, le plus grand point. Le centre attendra : joue d’abord dans le coin libre, sur la 3e ou la 4e ligne."}', array['D4','D3','C4','C3'], 'Le centre attendra', 'Blanc a pris le centre. Que joues-tu ?', 'Bravo ! Le coin en bas à gauche vaut plus que le centre : au centre, il faut beaucoup de pierres pour entourer un point. Le 3-3, le 3-4 et le 4-4 y sont tous bons.', 500),
 ('x08', null, 13, '{"rows":[".............",".............",".............","...X.....O...",".............",".............",".............",".............",".............","......X..O...",".............",".............","............."],"toPlay":"B","refutation":"Pas tout à fait. Blanc prend alors le coin en bas à gauche, le plus grand point, et ta pierre G4 reste seule. Joue d’abord dans le coin libre, sur la 3e ou la 4e ligne."}', array['D4','C4','D3','C3'], 'Le plus grand point', 'Chacun a joué deux pierres. Quel est le plus grand point ?', 'Bravo ! Le coin en bas à gauche était libre : c’est le plus grand point. Avec ta pierre G4, tu commences à entourer le bas. Le 3-3, le 3-4 et le 4-4 y sont tous bons.', 550)
on conflict (id) do nothing;
