-- Issue #16 : douze nouveaux problèmes communs en 9 × 9 (owner_id null), tous prouvés par src/go/problemes16.test.ts.
-- Capture (c1 à c4) : double atari, échelle, filet (geta), retour de capture (snapback).
-- Sauvetage (s1 à s4) : sortir de l'atari, relier, capturer la pierre qui coupe.
-- Vie et mort (v1 à v4) : faire deux yeux, tuer un groupe réduit à un œil.
-- Insertion seule : les six problèmes de base (b1 à b6) ne sont ni modifiés ni supprimés.
-- setup.refutation : texte affiché après une erreur (lu par l'appli, ignoré par les anciennes versions).
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('c1', null, 9, '{"rows":[".........","....O....",".........","...XTX...",".........","...XTX...",".........","....O....","........."],"toPlay":"B","refutation":"Pas tout à fait. Si tu mets une seule pierre en atari, Blanc joue E5 : il relie ses deux pierres et s''échappe. Cherche le point qui touche les deux."}', array['E5'], 'Double atari', 'Noir joue et capture. Un seul coup menace les deux pierres marquées à la fois.', 'Bravo ! En E5, tu mets les deux pierres en atari : il ne leur reste qu''une liberté, un seul point vide à côté d''elles. C''est un double atari. Blanc ne peut en sauver qu''une, et tu prends l''autre au coup suivant.', 450),
 ('c2', null, 9, '{"rows":[".........",".........",".........","....X....","...XT....",".....X...",".........","..O......","........."],"toPlay":"B","refutation":"Pas celle-là. Après F5, Blanc s''allonge en E4 et fuit vers le bas à gauche : la pierre blanche en C2 casse l''échelle, Blanc s''y relie et s''échappe. Pousse-le de l''autre côté."}', array['E4'], 'L''échelle cassée', 'Noir joue et capture. Attention à la pierre blanche en C2 : une seule des deux mises en atari marche.', 'Exact ! Blanc s''allonge en F5, et tu le remets en atari (une seule liberté) à chaque coup, en zigzag vers le haut à droite : c''est une échelle. Aucune pierre blanche ne l''attend sur ce chemin, il finit capturé contre le bord.', 850),
 ('c3', null, 9, '{"rows":[".........",".........",".........","....XX...","...XT....","...X.....",".........","......O..","........."],"toPlay":"B","refutation":"Pas tout à fait. Si tu mets en atari tout de suite, Blanc s''allonge et l''échelle qui suit bute sur la pierre blanche G2 : Blanc s''y relie et s''échappe. Joue un pas plus loin, en diagonale, pour l''enfermer."}', array['F4'], 'Le filet', 'Noir joue et capture. Mettre en atari tout de suite ne suffit pas.', 'Bien vu ! F4 ne touche pas la pierre, mais lui ferme la route : c''est un filet (geta en japonais). Si Blanc sort en F5, tu joues G5 ; s''il sort en E4, tu joues E3. Chaque fois, il est en atari (une seule liberté) et tu le captures.', 800),
 ('c4', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXX.....","OOTXOO...","O..OO...."],"toPlay":"B","refutation":"Pas tout à fait. Après B1, Blanc prend ta pierre en C1 et se relie à ses pierres D1 et E1 : il s''échappe. Sacrifie plutôt ta pierre au point qui touche aussi ces pierres-là."}', array['C1'], 'Le retour de capture', 'Noir joue et capture. Le groupe marqué n’a que deux libertés, et Blanc menace de se relier en C1.', 'Superbe ! Ta pierre en C1 peut être prise, mais si Blanc la capture en B1, son groupe n''a plus qu''une liberté : C1. Tu y rejoues aussitôt et prends 5 pierres. C''est un retour de capture (snapback) : on sacrifie une pierre pour en prendre plus. Ce n''est pas un ko, car tu reprends plusieurs pierres, pas une seule.', 750),
 ('s1', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........",".........",".........","...OSO..."],"toPlay":"B","refutation":"Pas encore. Ta pierre n''a qu''une liberté, en E2 : si Blanc y joue, il la capture. Occupe ce point toi-même."}', array['E2'], 'Remonte vers le centre', 'Ta pierre marquée est en atari : il ne lui reste qu''une liberté. Sauve-la.', 'Oui ! En t''allongeant en E2, tes pierres ont 3 libertés : D2, F2 et E3. Une pierre en atari (une seule liberté) se sauve souvent en s''allongeant vers le centre, là où il y a de la place.', 400),
 ('s2', null, 9, '{"rows":[".........",".........",".........","...OOO...","..OS.SO..",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc peut couper en E5 : tes deux pierres sont séparées et doivent se défendre chacune de son côté. Le bon point, c''est celui que Blanc veut prendre."}', array['E5'], 'Relie tes pierres', 'Blanc menace de couper en E5 et de mettre tes deux pierres en atari d’un coup. Relie-les.', 'C''est ça ! En E5, tes trois pierres ne forment plus qu''un groupe, avec 3 libertés : D4, E4 et F4. Sinon, Blanc coupait en E5 et faisait un double atari : deux pierres en atari (une seule liberté) en même temps.', 500),
 ('s3', null, 9, '{"rows":[".........",".........","...O.....",".........","..OSOX...","...OX....",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Si tu t''allonges en D6, Blanc répond E6 : sa pierre qui coupe est sauvée et la tienne reste en danger. Capture d''abord la pierre qui coupe."}', array['E6'], 'Prends la pierre qui coupe', 'Ta pierre marquée est en atari. La pierre blanche qui la coupe est en atari, elle aussi.', 'Bravo ! En E6, tu captures la pierre blanche E5. Ta pierre retrouve des libertés (les points vides à côté d''elle) et, si Blanc la remet en atari en D6, tu te relies en E5. Capturer la pierre qui coupe, c''est souvent la meilleure façon de se sauver.', 650),
 ('s4', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","..OOO....",".OS.S.O..","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc peut couper tes pierres, et ta pierre C2, qui n''a que peu de libertés, finit capturée. Le point de coupe est aussi ton point de liaison."}', array['D2'], 'Relie sur le bord', 'Blanc menace de couper tes deux pierres marquées en D2. Relie-les.', 'Exact ! En D2, tes pierres forment un seul groupe avec 4 libertés : C1, D1, E1 et F2. Seule, la pierre C2 n''en avait que deux (les points vides à côté d''elle) : coupée, elle aurait été capturée.', 600),
 ('v1', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","OOOOO....","SXXXO....","...XO...."],"toPlay":"B","refutation":"Pas tout à fait. Après ce coup, Blanc peut jouer B1, au milieu de ton espace : il ne te reste qu''un œil, et ton groupe finit capturé. Le point clé est le même pour les deux joueurs."}', array['B1'], 'Deux yeux', 'Noir joue et vit. Ton groupe doit former deux yeux.', 'Parfait ! B1 coupe ton espace en deux yeux, A1 et C1. Un œil est un point vide entouré par tes pierres. Blanc ne peut jouer dans aucun des deux : ce serait un suicide. Ton groupe ne peut plus être capturé, il est vivant.', 550),
 ('v2', null, 9, '{"rows":[".........",".........",".........",".........",".........","OOO......","SXO......",".XXO.....","..XO....."],"toPlay":"B","refutation":"Pas tout à fait. Après ce coup, Blanc peut t''empêcher de faire deux yeux et ton groupe finit capturé. Cherche le point qui sépare l''espace en deux."}', array['A1'], 'Le coin en coude', 'Noir joue et vit. Trois points vides en forme de coude : où est le point clé ?', 'Bien joué ! En A1, tu obtiens deux yeux, A2 et B1. Un œil est un point vide entouré par tes pierres. Blanc ne peut jouer dans aucun des deux : ce serait un suicide. Ton groupe est vivant.', 700),
 ('v3', null, 9, '{"rows":[".XO...OX.",".XTOOOOX.",".XXXXXXX.",".........",".........",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue E9 et fait deux yeux, D9 et F9 : son groupe est vivant pour toujours."}', array['E9'], 'Un seul œil', 'Noir joue et tue. Empêche le groupe blanc de faire deux yeux.', 'Exact ! En E9, au milieu, tu empêches Blanc de faire deux yeux (deux points vides entourés par ses pierres). Avec un seul œil, son groupe ne peut pas vivre : quoi qu''il fasse, il finit capturé.', 600),
 ('v4', null, 9, '{"rows":[".....XO..",".....XOO.","......XOT","......XXX",".........",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue J9 et fait deux yeux, H9 et J8 : son groupe est vivant."}', array['J9'], 'Tue dans le coin', 'Noir joue et tue. Le groupe blanc a trois points vides en forme de coude.', 'Bravo ! J9 est le point clé du coude. Blanc ne peut plus faire deux yeux (deux points vides entourés par ses pierres) : quoi qu''il fasse, son groupe finit capturé.', 800)
on conflict (id) do nothing;
