-- Issue #136, lot G : relier deux groupes (menace de coupe, relier en capturant), 9 × 9, Noir au trait.
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-g.test.ts. Aucun seki, aucun ko.
-- Insertion seule : aucun problème existant n'est modifié ni supprimé.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('g01', null, 9, '{"rows":[".........",".........",".........",".........",".........","OOOOOO...","XSX.XSO..",".X.O.XO..",".....O..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D3 et coupe tes deux groupes : chacun, seul, n''a plus assez de libertés. Relie-les d''abord."}', array['D3'], 'Ferme la coupe', 'Blanc menace de couper tes deux groupes. Relie-les.', 'Bravo ! D3 est le point de coupe : si Blanc y joue, il sépare tes deux groupes. Couper, c''est jouer entre deux groupes adverses pour les séparer. En D3, tes pierres ne forment plus qu''un groupe, avec assez de libertés pour tenir. Quand l''adversaire menace de couper, relie d''abord.', 660),
 ('g02', null, 9, '{"rows":[".........",".........",".........",".........",".........","...X.....",".OOXOO...","OSSOSSO..","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en D1 : sa pierre de coupe retrouve des libertés, et tes deux groupes du bas restent séparés et en danger. Occupe-toi de la pierre D2."}', array['D1','C1','E1'], 'Relie en capturant', 'La pierre blanche D2 sépare tes deux groupes. Relie-les.', 'Exact ! La pierre D2 coupe tes deux groupes, mais elle est en atari : il ne lui reste qu''une liberté, D1. En D1, tu la captures : le point D2 devient à toi, Blanc ne peut plus y jouer, et tes groupes sont reliés. C1 et E1 marchent aussi : si Blanc s''allonge en D1, il reste en atari et tu le prends au coup suivant. Mais D1 est le plus simple.', 700)
on conflict (id) do nothing;
