-- Issue #136, lot N : problèmes pour débutants, difficulté 300 à 700, 9 × 9, Noir au trait.
-- Capturer en un ou deux coups (bord, coin, centre, plusieurs groupes), sauver une pierre en atari (s'allonger ou
-- capturer), ne pas se mettre soi-même en atari, choisir la bonne pierre à capturer.
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-n.test.ts. Aucun seki, aucun ko.
-- Insertion seule : aucun problème existant n'est modifié ni supprimé.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('n01', null, 9, '{"rows":[".........",".........","..X...O..","....X....","...XTX...","...XOX...","..O......",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Les deux pierres blanches n''ont qu''une liberté, E3. Si tu joues ailleurs, Blanc s''allonge en E3 et retrouve trois libertés."}', array['E3'], 'Deux pierres d’un coup', 'Capture la pierre marquée en un coup.', 'Bravo ! Les pierres E5 et E4 se touchent : elles forment une chaîne. Une chaîne partage ses libertés, les points vides juste à côté. Il n''en reste qu''une, E3 : la chaîne est en atari. Tu la remplis et tu captures les deux pierres.', 300),
 ('n02', null, 9, '{"rows":[".........",".........",".........","..X......",".XOX.....",".........",".........","......XXX","......TTT"],"toPlay":"B","refutation":"Pas tout à fait. En C4, tu prends une pierre, mais Blanc joue F1 : ses trois pierres du bas ont de nouveau deux libertés, E1 et F2."}', array['F1'], 'Le plus gros d’abord', 'Deux groupes blancs sont en atari (une seule liberté). Capture le plus gros, marqué, en un coup.', 'Bravo ! F1 remplit la dernière liberté des trois pierres du bas : tu les captures toutes. Quand deux groupes sont en atari, prends d''abord le plus gros.', 330),
 ('n03', null, 9, '{"rows":[".X.......","XOX......",".........","....O....","...OSO...",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Tu prends B8, mais Blanc joue E4 et capture ta pierre. Quand une de tes pierres est en atari, sauve-la d''abord."}', array['E4'], 'Sauve avant de prendre', 'Ta pierre marquée est en atari : il ne lui reste qu’une liberté. Sauve-la.', 'Bravo ! En E4, ta pierre s''allonge : tes deux pierres forment une chaîne avec trois libertés, D4, F4 et E3. Elle est hors de danger. Prendre B8 était tentant, mais Blanc aurait pris ta pierre en E4.', 360),
 ('n04', null, 9, '{"rows":["..O......",".OSO.....",".........",".........",".........",".......X.","......XOX",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue C7 et capture ta pierre. Sa seule liberté était C7 : c''est là qu''il fallait jouer."}', array['C7'], 'Vers le centre', 'Ta pierre marquée est en atari. Sauve-la.', 'Bravo ! C7 allonge ta pierre vers le centre. Tes deux pierres ont trois libertés, B7, D7 et C6 : elles respirent. La pierre blanche H3 est en atari aussi, mais elle peut attendre.', 380),
 ('n05', null, 9, '{"rows":[".........",".........","...O.....","..OSO....","..OSO....",".........",".........",".....OXO.","......O.."],"toPlay":"B","refutation":"Pas tout à fait. Tu sauves G2, mais Blanc joue D4 et capture tes deux pierres marquées. Sauve d''abord le groupe le plus gros."}', array['D4'], 'Sauve le plus gros', 'Deux de tes groupes sont en atari. Tu ne peux en sauver qu’un : sauve les pierres marquées, le plus gros.', 'Bravo ! D4 allonge tes deux pierres : la chaîne a trois libertés, C4, E4 et D3. Blanc prendra peut-être G2, mais c''est une seule pierre. Tu as gardé les deux autres.', 420),
 ('n06', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XX.......",".TX......","..X......"],"toPlay":"B","refutation":"Pas tout à fait. La pierre a deux libertés, A2 et B1. Si tu ne la mets pas en atari, Blanc s''allonge en B1 et garde deux libertés."}', array['A2','B1'], 'Deux chemins dans le coin', 'Capture la pierre marquée en deux coups au plus.', 'Bravo ! Il y avait deux bonnes réponses. En A2, la pierre n''a plus qu''une liberté, B1 : si elle s''y allonge, ses deux pierres n''ont plus que A1, et tu les prends. En B1, c''est la même chose de l''autre côté. Dans le coin, une pierre a peu de libertés.', 440),
 ('n07', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","....X....","...XT....","...X....."],"toPlay":"B","refutation":"Pas tout à fait. En E1, Blanc s''allonge en F2, vers le centre, et a trois libertés. Mets-le en atari de l''autre côté, pour le pousser vers le bord."}', array['F2'], 'Vers le bord', 'Capture la pierre marquée en deux coups au plus.', 'Bravo ! F2 met la pierre en atari : sa seule liberté est E1, sur le bord. Si Blanc s''y allonge, ses deux pierres n''ont qu''une liberté, F1, car ta pierre D1 bloque l''autre côté. Tu les captures en F1.', 460),
 ('n08', null, 9, '{"rows":[".........",".........",".........","....X....","...XT.X..",".....X...",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. En F5, Blanc s''allonge en E4 et a deux libertés, D4 et E3 : il s''échappe vers le bas. Pousse-le plutôt vers tes pierres."}', array['E4'], 'Vers tes pierres', 'Capture la pierre marquée en deux coups au plus.', 'Bravo ! E4 met la pierre en atari et la pousse vers tes pierres F4 et G5. Si Blanc s''allonge en F5, ses deux pierres n''ont plus qu''une liberté, F6. Tu les captures en F6.', 480),
 ('n09', null, 9, '{"rows":[".........",".........",".........","....XX...","...XTTX..","......X..",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. En F4, Blanc s''allonge en E4 et a deux libertés, D4 et E3 : il s''échappe vers la gauche. Pousse-le plutôt vers ta pierre G4."}', array['E4'], 'Deux pierres contre ton mur', 'Capture les pierres marquées en deux coups au plus.', 'Bravo ! E4 met les deux pierres en atari : leur seule liberté est F4. Si Blanc s''y allonge, ses trois pierres n''ont plus qu''une liberté, F3, car ta pierre G4 ferme la droite. Tu les captures en F3.', 490),
 ('n10', null, 9, '{"rows":[".........",".........",".........","....X....","...XT.O..","...X.....","....X....",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. En E4, Blanc joue F5 : sa pierre rejoint G5, et le groupe a cinq libertés. Coupe d''abord le chemin vers G5."}', array['F5'], 'Sépare-la de son amie', 'Capture la pierre marquée en deux coups au plus.', 'Bravo ! F5 met la pierre en atari et la sépare de G5. Sa seule liberté est E4. Si Blanc s''y allonge, ses deux pierres n''ont qu''une liberté, F4 : tes pierres D4 et E3 ferment le reste. Tu les captures en F4.', 500),
 ('n11', null, 9, '{"rows":["......X..","......XT.",".......X.",".........",".........",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. En H9, Blanc s''allonge en J8 et a deux libertés, J9 et J7. Mets-le en atari par le bord de droite."}', array['J8'], 'Le coin se referme', 'Capture la pierre marquée en deux coups au plus.', 'Bravo ! J8 met la pierre en atari : sa seule liberté est H9. Si Blanc s''y allonge, ses deux pierres n''ont plus que J9, dans le coin. Tu les captures en J9.', 520),
 ('n12', null, 9, '{"rows":[".........",".........",".........",".......X.","......XTX","......XT.",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. En J4, Blanc s''allonge en H3 et a trois libertés, G3, H2 et J3. Mets-le en atari par le bas, pour le pousser vers le bord."}', array['H3'], 'Deux pierres contre le bord', 'Capture les pierres marquées en deux coups au plus.', 'Bravo ! H3 met les deux pierres en atari : leur seule liberté est J4, sur le bord. Si Blanc s''y allonge, ses trois pierres n''ont plus qu''une liberté, J3. Tu les captures en J3.', 540),
 ('n13', null, 9, '{"rows":["..OS.....","..XOO....",".........",".........",".........",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Si tu t''allonges en E9, tes deux pierres n''ont qu''une liberté, F9 : tu te mets toi-même en atari, et Blanc les prend. Ailleurs, Blanc prend ta pierre en E9. Regarde plutôt la pierre C9."}', array['B9'], 'Ne te mets pas en atari', 'Ta pierre marquée est en atari. Sauve-la.', 'Bravo ! La pierre blanche C9 est en atari aussi : B9 la capture. Ta pierre a maintenant deux libertés, C9 et E9. Blanc ne peut pas jouer en C9 : sa pierre n''y aurait aucune liberté. Et s''il joue E9, tu relies en C9. En E9, tu te serais mis toi-même en atari.', 560),
 ('n14', null, 9, '{"rows":[".........",".........","O........","OX.......","SOX......",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. En A4, tes deux pierres n''ont que deux libertés : Blanc joue B4 et elles sont de nouveau en atari, contre le bord. Ailleurs, Blanc prend ta pierre en A4. Regarde plutôt la pierre B5."}', array['B4'], 'Capture pour sauver', 'Ta pierre marquée est en atari. Sauve-la.', 'Bravo ! La pierre blanche B5 est en atari : B4 la capture. Ta pierre a maintenant deux libertés, A4 et B5, et Blanc ne peut pas jouer en B5 : il n''y aurait aucune liberté. S''il joue A4, tu relies en B5. S''allonger en A4, le long du bord, ne donnait que deux libertés.', 580),
 ('n15', null, 9, '{"rows":[".........",".........",".........","...X.....","..XT.TX..",".....X...",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Si tu mets une seule pierre en atari, Blanc joue E5 : il relie ses deux pierres et le groupe a trois libertés. Joue le point entre elles."}', array['E5'], 'Double atari', 'Capture une des pierres marquées en deux coups au plus.', 'Bravo ! E5 met les deux pierres en atari en même temps : D5 n''a plus que D4, F5 n''a plus que F6. C''est un double atari. Blanc n''en sauve qu''une, tu captures l''autre.', 600),
 ('n16', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........",".........","...XTX...","..XO....."],"toPlay":"B","refutation":"Pas tout à fait. En E1, tu prends D1, mais Blanc s''allonge en E3, vers le centre, et a trois libertés. La pierre qui compte, c''est E2."}', array['E3'], 'Pas la plus facile', 'Capture la pierre marquée en deux coups au plus.', 'Bravo ! E3 met E2 en atari par le haut : sa seule liberté est E1. Si Blanc s''y allonge, il se relie à D1, mais ses trois pierres n''ont qu''une liberté, F1. Tu les captures en F1. Prendre D1 en E1 était plus facile, mais E2 s''échappait.', 630),
 ('n17', null, 9, '{"rows":[".X.......","OOX......","XX.......",".........",".........",".........","....OX...","...OSOX..","........."],"toPlay":"B","refutation":"Pas tout à fait. Tu prends deux pierres en A9, mais Blanc joue E1 et capture ta pierre. La pierre à prendre, c''est celle qui te met en atari."}', array['E1','F1'], 'La bonne pierre à prendre', 'Ta pierre marquée est en atari. Sauve-la.', 'Bravo ! La pierre blanche F2 est en atari : F1 la capture, et ta pierre respire. E1 marche aussi : tes deux pierres ont deux libertés, D1 et F1, et F2 reste en atari. Si Blanc joue D1, tu prends F2 en F1. Les deux pierres de A8 et B8 valent moins que ta pierre.', 660),
 ('n18', null, 9, '{"rows":[".........",".........","........X",".......XO",".......XO",".........",".OXO.....","OSOSO....","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue C1 : il sauve sa pierre qui coupe, et tes deux pierres restent en atari. Tu n''en sauves qu''une, il prend l''autre."}', array['C1'], 'Prends la pierre qui coupe', 'Tes deux pierres marquées sont en atari. Sauve-les toutes les deux.', 'Bravo ! La pierre blanche C2 coupe tes deux pierres, et elle est en atari : C1 la capture. Chacune de tes pierres a maintenant deux libertés. Blanc ne peut pas jouer en C2 : sa pierre n''y aurait aucune liberté. S''il attaque, tu relies en C2. J5 et J6 font deux pierres, mais la pierre qui coupe vaut plus.', 690)
on conflict (id) do nothing;
