-- Issue #136, lot O : milieu de courbe, difficulté 650 à 940, 9 × 9, Noir au trait.
-- Filet (geta), prise en retour, échelle (pierre relais, échelle cassée).
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-o.test.ts. Aucun seki, aucun ko.
-- Insertion seule : aucun problème existant n'est modifié ni supprimé.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('o01', null, 9, '{"rows":[".........",".........","...X.....","......O..","..XT.X...","...X.....",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en E5, ou en D6 si tu as joué E5 ou E4, et garde assez de libertés pour s''échapper. Ne touche pas la pierre : ferme ses deux sorties."}', array['E6'], 'Le filet', 'Capture la pierre marquée en trois coups au plus.', 'Bravo ! E6 ne touche pas la pierre, mais ferme ses deux sorties, D6 et E5 : c''est un filet (geta en japonais). Si Blanc sort en D6, tu joues C6 : il est en atari (une seule liberté). S''il s''allonge en E5, il l''est encore, et tu le prends en E4. S''il sort d''abord en E5, tu joues E4, puis C6.', 650),
 ('o02', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","..XXX....","..XT.X...","..XT.OOO."],"toPlay":"B","refutation":"Pas tout à fait. En E2, tu mets les pierres en atari, mais Blanc joue E1 : il les relie à ses pierres F1, G1 et H1, et le groupe respire. Joue plutôt en E1, même si Blanc peut prendre ta pierre."}', array['E1'], 'Donne une pierre, prends-en trois', 'Capture les pierres marquées en deux coups au plus.', 'Bravo ! En E1, ta pierre n''a qu''une liberté, E2 : Blanc peut la prendre. Mais ses pierres D2 et D1 sont en atari (une seule liberté), E2 elles aussi. S''il prend en E2, ses trois pierres n''ont plus qu''une liberté, E1. Tu rejoues en E1 et tu les captures. C''est la prise en retour : tu donnes une pierre pour en prendre trois.', 680),
 ('o03', null, 9, '{"rows":[".........",".........",".........","....X....",".O.......","..X.TX...","....X....",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en E5, ou en D4 si tu as joué E5 ou F5, et garde assez de libertés pour s''échapper. Ferme d''abord ses deux sorties, sans toucher la pierre."}', array['D5'], 'Ferme les deux sorties', 'Capture la pierre marquée en trois coups au plus.', 'Bravo ! D5 ferme les deux sorties de la pierre, D4 et E5, sans la toucher : c''est un filet (geta). Si Blanc sort en D4, tu joues D3 : il est en atari, et s''il s''allonge en E5, tu le prends en F5. S''il sort en E5, tu joues F5, puis D3.', 710),
 ('o04', null, 9, '{"rows":[".........","O........","O........","OX.......","..X......","TTX......","XX.......",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. En B5, tu mets les pierres en atari, mais Blanc joue A5 : il les relie à ses pierres du haut, et le groupe a trois libertés. Joue plutôt en A5, même si Blanc peut prendre ta pierre."}', array['A5'], 'Prise en retour sur le bord', 'Capture les pierres marquées en deux coups au plus.', 'Superbe ! En A5, ta pierre n''a qu''une liberté, B5. Blanc peut la prendre, mais ses deux pierres marquées sont en atari. S''il prend en B5, ses trois pierres n''ont plus qu''une liberté, A5. Tu rejoues en A5 et tu les captures. C''est une prise en retour.', 740),
 ('o05', null, 9, '{"rows":[".........",".........",".........",".....X...",".........","....XT..O",".....XX..",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en G4, ou en F5 si tu as joué G4 ou H4, et garde assez de libertés pour s''échapper. Ne touche pas la pierre : ferme ses deux sorties."}', array['G5'], 'Le filet sans toucher', 'Capture la pierre marquée en trois coups au plus.', 'Bravo ! G5 ferme les deux sorties de la pierre, F5 et G4 : c''est un filet. Si Blanc sort en F5, tu joues E5 : il est en atari, et s''il s''allonge en G4, tu le prends en H4. S''il sort en G4, tu joues H4, puis E5.', 770),
 ('o06', null, 9, '{"rows":["....XT.OO","....XT.XO",".....XX.O",".........",".........",".........",".........",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. En G8, tu mets les pierres en atari, mais Blanc joue G9 : il les relie à ses pierres de droite, et le groupe a deux libertés, H7 et J6. Joue plutôt en G9, même si Blanc peut prendre ta pierre."}', array['G9'], 'Prise en retour en haut', 'Capture les pierres marquées en deux coups au plus.', 'Superbe ! En G9, ta pierre n''a qu''une liberté, G8. Mais les pierres marquées sont en atari aussi. Si Blanc prend en G8, ses trois pierres n''ont plus qu''une liberté, G9 : tu rejoues en G9 et tu les captures. Tu donnes une pierre pour en prendre trois : c''est une prise en retour.', 800),
 ('o07', null, 9, '{"rows":[".........",".........",".........",".........",".....X...",".....TX..","....X....",".......X.","........."],"toPlay":"B","refutation":"Pas tout à fait. En F3, Blanc s''allonge en E4, vers le haut, loin de ta pierre H2 : il a deux libertés, D4 et E5, et tu ne le prends plus en quatre coups. Ailleurs, il s''allonge aussi en E4. Pousse-le plutôt vers H2."}', array['E4'], 'Vers ta pierre H2', 'Capture la pierre marquée en quatre coups au plus.', 'Bravo ! E4 met la pierre en atari et la pousse vers le bas. Si elle s''allonge en F3, tu joues F2 ; si elle s''allonge ensuite en G3, tu joues H3. Blanc n''a plus qu''une liberté, G2. S''il s''y allonge, ta pierre H2 lui ferme la route : il reste en atari, et tu le prends en G1. Une pierre qui aide ainsi une échelle s''appelle une pierre relais.', 830),
 ('o08', null, 9, '{"rows":[".........",".........","...XX....","....TX...",".........","....X....","...O.....",".........","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en E5, ou en D6 si tu as joué E5 ou F5, et garde assez de libertés pour s''échapper. Ne touche pas la pierre : ferme ses deux sorties."}', array['D5'], 'Le filet sous le mur', 'Capture la pierre marquée en trois coups au plus.', 'Bravo ! D5 ferme les deux sorties de la pierre, D6 et E5 : c''est un filet. Si Blanc sort en D6, tu joues C6 : il est en atari, et s''il s''allonge en E5, tu le prends en F5. S''il sort en E5, tu joues F5, puis C6.', 860),
 ('o09', null, 9, '{"rows":[".........",".........",".........",".........",".........","...X.....",".XT......","..X.O....","........."],"toPlay":"B","refutation":"Pas tout à fait. En C4, Blanc s''allonge en D3, vers sa pierre E2 : l''échelle est cassée, il s''y relie et s''échappe. Ailleurs, il s''allonge aussi en D3. Pousse-le plutôt vers le bord de gauche, où rien ne l''attend."}', array['D3'], 'Choisis le bon côté', 'Capture la pierre marquée en cinq coups au plus.', 'Superbe ! D3 met la pierre en atari et la pousse vers le bord de gauche. Chaque fois qu''elle s''allonge, tu la remets en atari : C5, puis B5, puis A5. Elle zigzague jusqu''au bord, et tu la prends en A2. C''est une échelle. En C4, tu la poussais vers la pierre blanche E2 : Blanc s''y relie, l''échelle est cassée.', 900),
 ('o10', null, 9, '{"rows":[".........",".........",".........",".........","....XX...",".....TX..","......X..",".........","....O...."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en F3, ou en E4 si tu as joué F3 ou F2, et garde assez de libertés pour s''échapper. Ne touche pas la pierre : ferme ses deux sorties."}', array['E3'], 'Le filet au bon endroit', 'Capture la pierre marquée en trois coups au plus.', 'Bravo ! E3 ne touche pas la pierre, mais ferme ses deux sorties, E4 et F3 : c''est un filet. Si Blanc sort en E4, tu joues D4 : il est en atari, et s''il s''allonge en F3, tu le prends en F2. S''il sort en F3, tu joues F2, puis D4.', 940)
on conflict (id) do nothing;
