-- Issue #136, lot G : relier deux groupes (menace de coupe, relier en capturant), 9 × 9, Noir au trait.
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-g.test.ts. Aucun seki, aucun ko.
-- Insertion seule : aucun problème existant n'est modifié ni supprimé.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('g01', null, 9, '{"rows":[".........",".........",".........",".........",".........","OOOOOO...","XSX.XSO..",".X.O.XO..",".....O..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D3 et coupe tes deux groupes : chacun, seul, n''a plus assez de libertés. Relie-les d''abord."}', array['D3'], 'Ferme la coupe', 'Blanc menace de couper tes deux groupes. Relie-les.', 'Bravo ! D3 est le point de coupe : si Blanc y joue, il sépare tes deux groupes. Couper, c''est jouer entre deux groupes adverses pour les séparer. En D3, tes pierres ne forment plus qu''un groupe, avec assez de libertés pour tenir. Quand l''adversaire menace de couper, relie d''abord.', 660),
 ('g02', null, 9, '{"rows":[".........",".........",".........",".........",".........","...X.....",".OOXOO...","OSSOSSO..","........."],"toPlay":"B","refutation":"Pas tout à fait. Blanc s''allonge en D1 : sa pierre de coupe retrouve des libertés, et tes deux groupes du bas restent séparés et en danger. Occupe-toi de la pierre D2."}', array['D1','C1','E1'], 'Relie en capturant', 'La pierre blanche D2 sépare tes deux groupes. Relie-les.', 'Exact ! La pierre D2 coupe tes deux groupes, mais elle est en atari : il ne lui reste qu''une liberté, D1. En D1, tu la captures : le point D2 devient à toi, Blanc ne peut plus y jouer, et tes groupes sont reliés. C1 et E1 marchent aussi : si Blanc s''allonge en D1, il reste en atari et tu le prends au coup suivant. Mais D1 est le plus simple.', 700),
 ('g03', null, 9, '{"rows":[".........",".........",".........",".........",".........","...X.....",".OOXOO...","OSSOSSO..",".O....O.."],"toPlay":"B","refutation":"Pas tout à fait. Ton groupe de gauche est en atari : sa seule liberté est C1. Si tu ne règles pas tout de suite, Blanc y joue et le capture. Cherche le coup qui sauve les deux groupes."}', array['D1'], 'Une pierre sauve tout', 'Ton groupe de gauche est en atari et celui de droite est faible. Un seul coup sauve les deux.', 'Superbe ! Ton groupe de gauche est en atari : il n''a qu''une liberté, C1. Mais la pierre blanche D2, qui sépare tes deux groupes, est en atari elle aussi : sa seule liberté est D1. En D1, tu la captures. Ton groupe de gauche retrouve une liberté en D2, Blanc ne peut plus y jouer, et tes deux groupes sont reliés. Capturer la pierre de coupe sauve tout d''un coup.', 750),
 ('g04', null, 9, '{"rows":[".........",".........",".........",".........",".........",".OOOOO...","OSX.SO...",".X.OXO...",".....O..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D3 et coupe : ton groupe E3-E2 n''a plus qu''une liberté, E1. Il est en atari et ne peut pas s''échapper. Relie-le d''abord."}', array['D3'], 'Le point de coupe', 'Ton petit groupe de droite est faible. Relie-le à ton groupe de gauche.', 'Bravo ! D3 relie tes deux groupes. Si Blanc y jouait, il couperait : ton groupe E3-E2 n''aurait plus qu''une liberté, E1, et serait en atari. Couper, c''est jouer entre deux groupes adverses pour les séparer. Relié, ton groupe a assez de libertés pour tenir.', 780),
 ('g05', null, 9, '{"rows":[".........",".........",".........",".........",".........","OOOOOO...","XS.XSO...",".XXO.XO..","....OXO.."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue C3 et coupe : ton groupe D3-E3 n''a plus qu''une liberté, E2, et Blanc le capture au coup suivant. Relie-le d''abord."}', array['C3'], 'Relie avant tout', 'Blanc menace de couper tes pierres marquées. Relie-les.', 'Exact ! C3 relie D3-E3 à ton groupe de gauche. Si Blanc y jouait, il couperait : D3-E3 n''aurait plus qu''une liberté, E2, et serait en atari. Ne te laisse pas distraire par tes pierres F2-F1 : elles sont en atari, mais les sauver en E2 ne fait qu''ajouter des pierres à un groupe qui n''a qu''une liberté, C3.', 820)
on conflict (id) do nothing;
