-- Issue #136, lot Q : vie et mort, difficulté 600 à 850, 9 × 9, Noir au trait.
-- Œil vrai et faux œil, espace ouvert sur le bord.
-- Problèmes communs (owner_id null), tous prouvés par src/go/lot-q.test.ts (outil src/go/preuve-vie-mort.ts).
-- Aucun seki, aucun ko. Insertion seule : aucun problème existant n'est modifié ni supprimé.
-- setup.refutation : texte affiché après une erreur.
-- La table puzzles garde sa RLS (activée dans 20260926235308_progression_problemes_lecons_badges).
insert into public.puzzles (id, owner_id, size, setup, answers, title, prompt, explanation, difficulty) values
 ('q01', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","OOOOOO...","XSX.OO...",".X.XXO..."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue D2 : tes pierres D1 et E1 n''ont plus qu''une liberté, C1. Blanc peut les prendre, donc C1 est un faux œil. Avec un seul vrai œil, ton groupe finit capturé."}', array['D2'], 'Rends ton œil vrai', 'Noir joue et vit. Tu as deux yeux, A1 et C1. Mais C1 est-il un vrai œil ?', 'Bravo ! D2 relie D1 et E1 au reste de ton groupe. A1 et C1 sont alors deux vrais yeux : deux points vides entourés par tes pierres, où Blanc ne peut pas jouer. Avec deux vrais yeux, ton groupe est vivant : il ne peut plus être capturé.', 600),
 ('q02', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXXXXXX.","XTOOO.XX.","XO.O.OOX."],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue F2 et relie F1 et G1 à son groupe. C1 et E1 sont alors deux vrais yeux : le groupe blanc est vivant, il ne peut plus être capturé."}', array['F2'], 'Rends l’œil faux', 'Noir joue et tue. Blanc a deux yeux, C1 et E1. Regarde les coins de E1.', 'Bravo ! F2 touche E1 par le coin. Les pierres F1 et G1 n''ont plus qu''une liberté, E1 : tu peux les prendre. E1 est donc un faux œil, il ne compte pas. Blanc n''a qu''un vrai œil, C1 (un point vide entouré par ses pierres), et son groupe finit capturé.', 700),
 ('q03', null, 9, '{"rows":[".........",".........",".........",".........",".........",".........","XXXXXXXXX","XTOOOOOOX","XO.....XX"],"toPlay":"B","refutation":"Pas tout à fait. Blanc joue G1, ou D1 si tu as joué E1. Il garde assez de place pour deux yeux : son groupe est vivant. Joue en G1 ou en D1 avant lui."}', array['D1','G1'], 'Cinq points sur le bord', 'Noir joue et tue. Blanc a cinq points vides, de C1 à G1. Ta pierre H1 touche G1.', 'Superbe ! Deux coups marchent. En G1, tu réduis l''espace à quatre points, et F1 touche ta pierre : Blanc n''a plus la place pour deux yeux (deux points vides entourés par ses pierres). En D1, tu joues au milieu de son espace et tu l''empêches de le couper en deux yeux. Dans les deux cas, son groupe finit capturé.', 850)
on conflict (id) do nothing;
